### ISSUE TITLE
GPM not reachable

### ISSUE THREAD

**Issue by dimlau** [getgrav/grav#1008]
[2016-08-26 13:39:39] grav.CRITICAL: An exception has been thrown during the rendering of a template ("GPM not reachable. Please check your internet connection or check the Grav site is reachable") in "partials/plugins-list.html.twig" at line 19. - Trace: #0 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) #1 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code(218): Twig_Template->display(Array) #2 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Template.php(167): __TwigTemplate_8b75f437169b28aa0f432a531a8bbd5d55e9ab45e32c7ebed1a94a6e1ce96951->block_content(Array, Array) #3 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code(198): Twig_Template->displayBlock('content', Array, Array) #4 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Template.php(167): __TwigTemplate_22d4a31ad21e6a0bb7a3271732673cbe420395e0c4031fe6fea7feb205bc15fd->block_page(Array, Array) #5 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code(151): Twig_Template->displayBlock('page', Array, Array) #6 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Template.php(167): __TwigTemplate_22d4a31ad21e6a0bb7a3271732673cbe420395e0c4031fe6fea7feb205bc15fd->block_body(Array, Array) #7 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code(41): Twig_Template->displayBlock('body', Array, Array) #8 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Template.php(387): __TwigTemplate_22d4a31ad21e6a0bb7a3271732673cbe420395e0c4031fe6fea7feb205bc15fd->doDisplay(Array, Array) #9 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) #10 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code(63): Twig_Template->display(Array, Array) #11 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Template.php(387): __TwigTemplate_8b75f437169b28aa0f432a531a8bbd5d55e9ab45e32c7ebed1a94a6e1ce96951->doDisplay(Array, Array) #12 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) #13 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Template.php(366): Twig_Template->display(Array) #14 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Environment.php(347): Twig_Template->render(Array) #15 /home/wwwroot/kaixin/system/src/Grav/Common/Twig/Twig.php(340): Twig_Environment->render('plugins.html.tw...', Array) #16 /home/wwwroot/kaixin/system/src/Grav/Common/Service/OutputServiceProvider.php(19): Grav\Common\Twig\Twig->processSite(NULL) #17 /home/wwwroot/kaixin/vendor/pimple/pimple/src/Pimple/Container.php(113): Grav\Common\Service\OutputServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #18 /home/wwwroot/kaixin/system/src/Grav/Common/Processors/RenderProcessor.php(17): Pimple\Container->offsetGet('output') #19 /home/wwwroot/kaixin/system/src/Grav/Common/Grav.php(121): Grav\Common\Processors\RenderProcessor->process() #20 /home/wwwroot/kaixin/system/src/Grav/Common/Grav.php(396): Grav\Common\Grav->Grav\Common\{closure}() #21 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('render', 'Render', Object(Closure)) #22 /home/wwwroot/kaixin/system/src/Grav/Common/Grav.php(372): call_user_func_array(Object(Closure), Array) #23 /home/wwwroot/kaixin/system/src/Grav/Common/Grav.php(122): Grav\Common\Grav->__call('measureTime', Array) #24 /home/wwwroot/kaixin/system/src/Grav/Common/Grav.php(122): Grav\Common\Grav->measureTime('render', 'Render', Object(Closure)) #25 /home/wwwroot/kaixin/index.php(45): Grav\Common\Grav->process() #26 {main} [] []
[2016-08-26 13:51:58] grav.CRITICAL: An exception has been thrown during the rendering of a template ("GPM not reachable. Please check your internet connection or check the Grav site is reachable") in "partials/themes-list.html.twig" at line 21. - Trace: #0 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) #1 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code(204): Twig_Template->display(Array) #2 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Template.php(167): __TwigTemplate_0def82b009bdd2f615e1ef2e09a1b71bb3cd15087f9776dc3c8724ce4300b46f->block_content(Array, Array) #3 /home/wwwroot/kaixin/cache/twig/a1/a1f846d14472f3ff27ab68743c2dad9c313b7e1f076e19b0bbd8a29b8fbbf6a5.php(198): Twig_Template->displayBlock('content', Array, Array) #4 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Template.php(167): __TwigTemplate_22d4a31ad21e6a0bb7a3271732673cbe420395e0c4031fe6fea7feb205bc15fd->block_page(Array, Array) #5 /home/wwwroot/kaixin/cache/twig/a1/a1f846d14472f3ff27ab68743c2dad9c313b7e1f076e19b0bbd8a29b8fbbf6a5.php(151): Twig_Template->displayBlock('page', Array, Array) #6 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Template.php(167): __TwigTemplate_22d4a31ad21e6a0bb7a3271732673cbe420395e0c4031fe6fea7feb205bc15fd->block_body(Array, Array) #7 /home/wwwroot/kaixin/cache/twig/a1/a1f846d14472f3ff27ab68743c2dad9c313b7e1f076e19b0bbd8a29b8fbbf6a5.php(41): Twig_Template->displayBlock('body', Array, Array) #8 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Template.php(387): __TwigTemplate_22d4a31ad21e6a0bb7a3271732673cbe420395e0c4031fe6fea7feb205bc15fd->doDisplay(Array, Array) #9 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) #10 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code(61): Twig_Template->display(Array, Array) #11 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Template.php(387): __TwigTemplate_0def82b009bdd2f615e1ef2e09a1b71bb3cd15087f9776dc3c8724ce4300b46f->doDisplay(Array, Array) #12 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) #13 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Template.php(366): Twig_Template->display(Array) #14 /home/wwwroot/kaixin/vendor/twig/twig/lib/Twig/Environment.php(347): Twig_Template->render(Array) #15 /home/wwwroot/kaixin/system/src/Grav/Common/Twig/Twig.php(340): Twig_Environment->render('themes.html.twi...', Array) #16 /home/wwwroot/kaixin/system/src/Grav/Common/Service/OutputServiceProvider.php(19): Grav\Common\Twig\Twig->processSite(NULL) #17 /home/wwwroot/kaixin/vendor/pimple/pimple/src/Pimple/Container.php(113): Grav\Common\Service\OutputServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #18 /home/wwwroot/kaixin/system/src/Grav/Common/Processors/RenderProcessor.php(17): Pimple\Container->offsetGet('output') #19 /home/wwwroot/kaixin/system/src/Grav/Common/Grav.php(121): Grav\Common\Processors\RenderProcessor->process() #20 /home/wwwroot/kaixin/system/src/Grav/Common/Grav.php(396): Grav\Common\Grav->Grav\Common\{closure}() #21 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('render', 'Render', Object(Closure)) #22 /home/wwwroot/kaixin/system/src/Grav/Common/Grav.php(372): call_user_func_array(Object(Closure), Array) #23 /home/wwwroot/kaixin/system/src/Grav/Common/Grav.php(122): Grav\Common\Grav->__call('measureTime', Array) #24 /home/wwwroot/kaixin/system/src/Grav/Common/Grav.php(122): Grav\Common\Grav->measureTime('render', 'Render', Object(Closure)) #25 /home/wwwroot/kaixin/index.php(45): Grav\Common\Grav->process() #26 {main} [] []
[2016-08-26 13:54:06] grav.CRITICAL: Call to a member function filter() on null - Trace: #0 /home/wwwroot/kaixin/vendor/filp/whoops/src/Whoops/Run.php(363): Whoops\Run->handleError(1, 'Call to a membe...', '/home/wwwroot/k...', 477) #1 [internal function]: Whoops\Run->handleShutdown() #2 {main} [] []

**Comment by flaviocopes** [comment]
Did you check https://learn.getgrav.org/troubleshooting/common-problems#cannot-connect-to-the-gpm already?

**Comment by dimlau** [comment]
![2016-08-29 2 19 17](https://cloud.githubusercontent.com/assets/396423/18042414/ced9deb6-6df3-11e6-8494-b5ee44501c80.png)


![2016-08-29 2 18 59](https://cloud.githubusercontent.com/assets/396423/18042415/d1255cd6-6df3-11e6-9845-cf1db28ba234.png)


![2016-08-29 2 22 39](https://cloud.githubusercontent.com/assets/396423/18042495/46d90086-6df4-11e6-8165-b54bdc4b7b4c.png)


![2016-08-29 2 23 57](https://cloud.githubusercontent.com/assets/396423/18042493/467a9e9c-6df4-11e6-9cb9-cb664a8da135.png)


……………………
:(

**Comment by w00fz** [comment]
Are you behind proxy?
Also can you try running the command `curl -I https://getgrav.org/downloads/plugins.json` in your terminal and see what you get?

**Comment by dimlau** [comment]
![2016-08-29 2 42 06](https://cloud.githubusercontent.com/assets/396423/18042908/ccb07c8c-6df6-11e6-8ca1-3cb8dc13b30a.png)

So ...that's the problem?

**Comment by w00fz** [comment]
For you, yes. It's a bit weird because I don't get that CERT issue and further more I'm failing to see how calling `getgrav.org` would have anything to do with `demo.getgrav.org`.

Do you have a different server, or your computer even if you're on Linux/Mac, where you can try that command on?

**Comment by dimlau** [comment]
I'm useing a iMac.

![1](https://cloud.githubusercontent.com/assets/396423/18046371/280a5a22-6e0a-11e6-9405-4627dacb32a9.jpg)

So... it means my VPS has something wrong?

**Comment by dimlau** [comment]
![2](https://cloud.githubusercontent.com/assets/396423/18046490/bc2be1da-6e0a-11e6-8e4c-12becf20f046.jpg)

**Comment by w00fz** [comment]
Yes something looks wrong on your VPS, you should be getting the same response as on your Mac.
Which hosting provider is it?

Also it's normal for it to respond ok when going through `http` only as the issue seems strictly related to SSL certificates.

**Comment by flaviocopes** [comment]
Re `demo.getgrav.org`, sometimes I get the same reference in Little Snitch - sometimes it's demo.getgrav.org, sometimes it's learn.getgrav.org, sometimes getgrav.org - I thought it was some cached resource name in Little Snitch, but maybe it's something else.

**Comment by w00fz** [comment]
@dimlau can you run this command from the machine where you get the error and paste back the output?

``` bash
echo | openssl s_client -showcerts -servername getgrav.org -connect getgrav.org:443 2>/dev/null | openssl x509 -inform pem -noout -text
```

**Comment by w00fz** [comment]
Any update on this @dimlau ?

**Comment by w00fz** [comment]
I'm assuming everything worked out for the best. The issue didn't seem related to Grav itself but to the VPS for this reason I'm going to close the issue.

However, if you have other comments regarding what might have caused that and how you resolved it, I would be very interested to know.

Cheers.

**Comment by judhi** [comment]
Same symptom happened to me. Contacted my hosting support and at first they were confused. Later on they said it's because my VPS runs old openssl & curl version that can't be upgraded on CentOS 5.11. To complicate the matter, they said that CentOS 5.11 can't be upgraded. Solution they offer is to buy new hosting plan with new OS and do the migration. How does that sound to you?

Here's the excerpt:

> Thank you for getting back to us. I have checked further on the issue and noticed that your server is the older CentOS 5.11 version. This uses an older version of openssl and curl. This has limitation and openssl can't be upgraded to a newer version as it break a lot of things on the server. The only way around this is to purchase a newer VPS subscription with a newer version of CentOS 6.8 and with same configuration and WHM control panel. You can then use the Transfer tool to migrate your websites to this new VPS. Once everything is migrated, you can then cancel this old subscription. Unfortunately, this is the only way around your issue.

**Comment by w00fz** [comment]
That is unfortunate. However I believe I was able to circumvent most of this SSL issues and I already provided a fix with #1053.

By disabling the verify peer you will be able, hopefully, to get through with GPM no matter the curl and ssl version.

We hope to get this release out soon in the meantime you could try following this thread where I provide gruidance on how to approach the problem, hopefully it will work for you too. See #1044.

**Comment by judhi** [comment]
Thanks. I tried those tips on #1053 but still getting the same error message. Running curl with -k option did the trick though. Maybe I just missed some config lines? Will check again.

**Comment by w00fz** [comment]
Yah -k is what I now made available as an option to opt-out of the peer verification.

See also https://github.com/getgrav/grav/commit/c4f71c9ddab5d3066948d2b16ba2047ef51cb89c or force the method to `method: 'curl'`.

**Comment by qwertologe** [comment]
Same problem here - no internet connection (local installation in Apache).

```
Twig_Error_Runtime thrown with message "An exception has been thrown during the rendering of a template ("GPM not reachable. Please check your internet connection or check the Grav site is reachable")."

Stacktrace:
#29 Twig_Error_Runtime in /var/www/grav/user/plugins/admin/themes/grav/templates/partials/plugins-list.html.twig:20
#28 RuntimeException in /var/www/grav/system/src/Grav/Common/GPM/GPM.php:473
#27 Grav\Common\GPM\GPM:findPackage in /var/www/grav/vendor/twig/twig/lib/Twig/Template.php:674
#26 Twig_Template:getAttribute in /var/www/grav/cache/twig/fb/fb5572b997bfcd3e35e15dc32e5d9d4730f196eff7aed6e343570e7522d9f85b.php:74
#25 __TwigTemplate_4ffa6469cdac6a97a82e73ae69ed80a16a44afc3862582b1e6e148fe7fc59ea6:doDisplay in /var/www/grav/vendor/twig/twig/lib/Twig/Template.php:432
#24 Twig_Template:displayWithErrorHandling in /var/www/grav/vendor/twig/twig/lib/Twig/Template.php:403
#23 Twig_Template:display in /var/www/grav/cache/twig/f1/f1b2ce69f38f182e8b3e2f93eba6a286f3096097b1b8c6b5e5b3264a9c7ea8e6.php:215
#22 __TwigTemplate_5f8b548c5f83a5134d3d3500c05e24f691251132c77afad56e1d546ec5c8d25e:block_content in /var/www/grav/vendor/twig/twig/lib/Twig/Template.php:215
#21 Twig_Template:displayBlock in /var/www/grav/cache/twig/e0/e005f1f0b220aa92483fc0163aeafc3919e1000402ecb9e2792c9b2f7704127a.php:205
#20 __TwigTemplate_4f32b7ae439ddfa3478dc4f23f7e0159bbedc490f967e296537470c32aea3e56:block_page in /var/www/grav/vendor/twig/twig/lib/Twig/Template.php:215
#19 Twig_Template:displayBlock in /var/www/grav/cache/twig/e0/e005f1f0b220aa92483fc0163aeafc3919e1000402ecb9e2792c9b2f7704127a.php:158
#18 __TwigTemplate_4f32b7ae439ddfa3478dc4f23f7e0159bbedc490f967e296537470c32aea3e56:block_body in /var/www/grav/vendor/twig/twig/lib/Twig/Template.php:215
#17 Twig_Template:displayBlock in /var/www/grav/cache/twig/e0/e005f1f0b220aa92483fc0163aeafc3919e1000402ecb9e2792c9b2f7704127a.php:45
#16 __TwigTemplate_4f32b7ae439ddfa3478dc4f23f7e0159bbedc490f967e296537470c32aea3e56:doDisplay in /var/www/grav/vendor/twig/twig/lib/Twig/Template.php:432
#15 Twig_Template:displayWithErrorHandling in /var/www/grav/vendor/twig/twig/lib/Twig/Template.php:403
#14 Twig_Template:display in /var/www/grav/cache/twig/f1/f1b2ce69f38f182e8b3e2f93eba6a286f3096097b1b8c6b5e5b3264a9c7ea8e6.php:63
#13 __TwigTemplate_5f8b548c5f83a5134d3d3500c05e24f691251132c77afad56e1d546ec5c8d25e:doDisplay in /var/www/grav/vendor/twig/twig/lib/Twig/Template.php:432
#12 Twig_Template:displayWithErrorHandling in /var/www/grav/vendor/twig/twig/lib/Twig/Template.php:403
#11 Twig_Template:display in /var/www/grav/vendor/twig/twig/lib/Twig/Template.php:411
#10 Twig_Template:render in /var/www/grav/vendor/twig/twig/lib/Twig/Environment.php:362
#9 Twig_Environment:render in /var/www/grav/system/src/Grav/Common/Twig/Twig.php:348
#8 Grav\Common\Twig\Twig:processSite in /var/www/grav/system/src/Grav/Common/Service/OutputServiceProvider.php:18
#7 Grav\Common\Service\OutputServiceProvider:Grav\Common\Service\{closure} in /var/www/grav/vendor/pimple/pimple/src/Pimple/Container.php:113
#6 Pimple\Container:offsetGet in /var/www/grav/system/src/Grav/Common/Processors/RenderProcessor.php:17
#5 Grav\Common\Processors\RenderProcessor:process in /var/www/grav/system/src/Grav/Common/Grav.php:122
#4 Grav\Common\Grav:Grav\Common\{closure} in /var/www/grav/system/src/Grav/Common/Grav.php:364
#3 Grav\Common\Grav:Grav\Common\{closure} in /var/www/grav/system/src/Grav/Common/Grav.php:340
#2 call_user_func_array in /var/www/grav/system/src/Grav/Common/Grav.php:340
#1 Grav\Common\Grav:__call in /var/www/grav/system/src/Grav/Common/Grav.php:123
#0 Grav\Common\Grav:process in /var/www/grav/index.php:51
```

In my opinion, Grav should work without connection to the internet - dokuwiki does.

**Comment by flaviocopes** [comment]
@qwertologe is not related to the OP problem, but I replicated. Plugins and themes list were not working, even to access the configuration. The 2 commits above, in Admin and in Core Grav, fix the problem.

**Comment by Kuurusch** [comment]
@flaviocopes Ok, sorry now I'm also hear, after I found the Problem in #931 :/ 
With your commits the connection problems is still not solve, is that right? 

I tried curl -I https://getgrav.org/downloads/plugins.json and got:
curl: (51) Cert verify failed: BADCERT_NOT_TRUSTED

If I trie:
echo | openssl s_client -showcerts -servername getgrav.org -connect 
getgrav.org:443 2>/dev/null | openssl x509 -inform pem -noout -text 

I got:
Policy: 1.3.6.1.4.1.44947.1.1.1
                  CPS: http://cps.letsencrypt.org
                  User Notice:
                    Explicit Text: This Certificate may only be relied upon by Relying Parties and only in accordance with the Certificate Policy found at https://letsencrypt.org/repository/

    Signature Algorithm: sha256WithRSAEncryption
         89:e1:2e:71:5b:9d:8d:db:b9:82:58:50:1c:79:3c:ed:a9:db:
         13:43:a1:fd:81:b1:bd:86:07:bb:8d:32:a6:7e:4b:7e:0d:bc:
         d6:b2:06:bf:16:2d:f4:1c:14:b4:8e:69:cc:6f:77:a8:61:b0:
         ec:ae:6c:9b:71:13:65:b7:d1:2b:13:fb:f2:73:c1:1c:05:c0:
         6f:29:ae:34:ef:e4:9c:a6:83:80:b3:86:84:ee:24:7d:bb:93:
         12:a8:93:04:a0:df:3b:55:2d:99:8e:fb:37:93:58:46:94:20:
         30:c7:a5:7d:a7:bc:74:db:7e:f6:7a:2a:06:69:52:b1:49:e8:
         8d:2a:20:10:21:34:8f:4d:00:4e:2b:ac:90:4b:d5:5b:0d:0f:
         62:3a:c7:c4:81:3b:43:ac:68:a2:f8:29:90:16:0d:f9:6c:27:
         4d:bd:4a:eb:c8:3e:30:ea:5c:d8:ae:21:cf:1d:d9:1f:a5:58:
         c6:b3:26:24:5e:05:f3:0a:6d:0b:80:ac:fe:91:91:f6:2e:ba:
         4e:3c:5e:9e:e5:75:9f:d2:25:56:20:8e:55:7d:94:53:62:5b:
         fa:f1:ff:c0:e5:fd:c8:b6:ee:05:3d:a3:e8:e8:8d:e6:27:81:
         03:b9:98:1c:b0:8d:f8:34:2c:81:a4:60:7b:42:a4:90:9f:34:
         e3:e2:be:4b

Any ideas?

**Comment by flaviocopes** [comment]
Might be an old SSL release problem. Did you already try turning off system.gpm.verify_peer as suggested previously?

**Comment by Kuurusch** [comment]
UUUffff, thanks, yea now it worked. Is not a optimal solution I think but it works. Tried it already before but had at the same Time also a proxy deposited and because of that it didn't worked somehow...

**Comment by qwertologe** [comment]
@flaviocopes

Thanks, now it works - even during during train ride (flapping connection).

But another problem remains: The font for the content changes - here it is TeX Gyre Heros without  and Raleway with internet connection. A solution could be: https://github.com/getgrav/grav-theme-antimatter/issues/88

**Comment by flaviocopes** [comment]
Yes, that's another issue, specific to the theme. The theme should provide a local font.
