### ISSUE TITLE
extract error during upgrade installation

### ISSUE THREAD

**Issue by jens-t** [getgrav/grav#1920]
following error occurs:
```
Preparing to upgrade to v1.4.1..
  |- Downloading upgrade [3.28M]...   100%
  |- Installing upgrade...    error                             
  |  '- An error occurred while extracting the package
  '- Installation failed or aborted.
```

i tried --verbose, set errors to true in system.yaml, nothing inside the logs, only "An error occurred while extracting the package".

has anyone an idea how i can get decent error information, what's failing during extraction?

Thanks!

Edit: I think it's a permission problem, but i dont know how to get the tmp path where the files are extracted to ...

**Comment by rhukster** [comment]
The code where this can be set is in the `Grav\Common\GPM\Installer.php`:

```
public static function unZip($zip_file, $destination)
    {
        $zip = new \ZipArchive();
        $archive = $zip->open($zip_file);

        if ($archive === true) {
            Folder::mkdir($destination);

            $unzip = $zip->extractTo($destination);


            if (!$unzip) {
                self::$error = self::ZIP_EXTRACT_ERROR;
                Folder::delete($destination);
                $zip->close();
                return false;
            }

            $package_folder_name = preg_replace('#\./$#', '', $zip->getNameIndex(0));
            $zip->close();
            $extracted_folder = $destination . '/' . $package_folder_name;

            return $extracted_folder;
        }

        self::$error = self::ZIP_EXTRACT_ERROR;
```

Basically, all we're doing is trying to open the zip file, if that archive is false, this error gets set.

The temp folder used is `$tmp_dir = Grav::instance()['locator']->findResource('tmp://', true, true);` so this is usually `tmp/` in your Grav installation.

I have got a [Pull Requst](https://github.com/getgrav/grav/pull/1922/files) where i've added more verbose error code handling, perhaps you could test with that?

**Comment by jens-t** [comment]
Thanks for the fast answer! That PR looks promising, will try that :)

I already tried to debug the `Grav\Common\GPM\Installer.php` but i didn't succeed in getting some additional debug output into the shell. Are the cli scripts cached in some way? Or, is there a simple way to dump some debug information triggered from the `Grav\Common\GPM\Installer.php` to the shell, when using `bin/gpm selfupgrade`?

**Comment by rhukster** [comment]
You can dump to the log file by inserting:

```
Grav::instance()['log']->notice('My notice message');
```

in the code.  Or if you in GPM, you can simply `echo()` stuff and it will display in the console as output.

**Comment by jens-t** [comment]
Thanks, that was the information i was looking for!

**Comment by jens-t** [comment]
I tested `Grav::instance()['log']->notice('My notice message');`, it doesn't create a log file under /logs ...
And `echo()` doesn't work for displaying debug infomation in the shell ...

@rhukster Are you sure the Installer.php isn't cached in some way?

Thanks.

**Comment by jens-t** [comment]
If i test with the PR, i get:
```
PHP Fatal error:  Uncaught Error: Class 'Grav\Common\GPM\ZipArchive' not found in /var/www/sophora-docs/system/src/Grav/Common/GPM/Installer.php:206
Stack trace:
#0 /var/www/sophora-docs/system/src/Grav/Common/GPM/Installer.php(193): Grav\Common\GPM\Installer::getZipError(19)
#1 /var/www/sophora-docs/system/src/Grav/Common/GPM/Installer.php(97): Grav\Common\GPM\Installer::unZip('/var/www/sophor...', '/var/www/sophor...')
#2 /var/www/sophora-docs/system/src/Grav/Console/Gpm/SelfupgradeCommand.php(219): Grav\Common\GPM\Installer::install('/var/www/sophor...', '/var/www/sophor...', Array)
#3 /var/www/sophora-docs/system/src/Grav/Console/Gpm/SelfupgradeCommand.php(177): Grav\Console\Gpm\SelfupgradeCommand->upgrade()
#4 /var/www/sophora-docs/system/src/Grav/Console/ConsoleCommand.php(29): Grav\Console\Gpm\SelfupgradeCommand->serve()
#5 /var/www/sophora-docs/vendor/symfony/console/Command/Command.php(266): Grav\Console\ConsoleCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ in /var/www/sophora-docs/system/src/Grav/Common/GPM/Installer.php on line 206
```

**Comment by rhukster** [comment]
Ok, that lack of `\` was a legitimate issue... fixed in develop btw.

The face you get a success is very strange.  Did you manage to add some logging statements to track down where things are going wonky?

**Comment by jens-t** [comment]
> Did you manage to add some logging statements to track down where things are going wonky?

Not really, tryin again now ... It's installed in a corporate network, so i can only investigate in the beginning of each week.

**Comment by jens-t** [comment]
Ah, debugging works now and i found out that the errorcode `19` is returned from `ZipArchive::open` ... dont know what it means yet, still investigating ...

**Comment by jens-t** [comment]
Ok, so the "success but no success" error is caused by:
```
-        self::$error = self::ZIP_EXTRACT_ERROR; // -> returns integer
+        self::$error = self::getZipError($archive); // -> returns error string
```

**Comment by jens-t** [comment]
if i run `unzip grav-update-v1.4.2.zip`:
it generates following output:
``` 
Archive:  grav-update-v1.4.2.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of grav-update-v1.4.2.zip or
        grav-update-v1.4.2.zip.zip, and cannot find grav-update-v1.4.2.zip.ZIP, period.
```

**Comment by jens-t** [comment]
the download with wget works fine, taking a closer look in the Response Class ...

**Comment by rhukster** [comment]
@jens-t simply edit the file on grav develop branch directly in GitHub. Then when comitting it creates a fork and pull request automatically.

**Comment by jens-t** [comment]
ok, thanks for the info!
