### ISSUE TITLE
Preview in Admin Plugin broken

### ISSUE THREAD

**Issue by TobiasScheinert** [getgrav/grav#1930]
Hi,

Version `1.7.0` works
```
---------------------------------------------------------------
| Count | Name         | Slug  | Version          | Installed |
===============================================================
| 1     | Admin Panel  | admin | v1.7.0 -> v1.7.1 | installed |
---------------------------------------------------------------
```
after an upgrade:
```
------------------------------------------------------
| Count | Name         | Slug  | Version | Installed |
======================================================
| 1     | Admin Panel  | admin | v1.7.1  | installed |
------------------------------------------------------
```
`0 - An exception has been thrown during the rendering of a template ("Undefined index: HTTP_REFERER").`

Log output:
```
[2018-03-19 22:43:46] grav.CRITICAL: An exception has been thrown during the rendering of a template ("Undefined index: HTTP_REFERER"). - Trace: #0 /path/to/webpage/cache/twig/f0/f06ae2f5b2803384507c810b0c39e41f628ed5ee8ccf6e87cb7440dcf1bca162.php(195): Twig_Template->displayBlock('titlebar', Array, Array)
#1 /path/to/webpage/vendor/twig/twig/lib/Twig/Template.php(215): __TwigTemplate_971c1000ff0ad781c34e7a9b752181f10b47bed1688dcc756b57404e69ec239d->block_page(Array, Array)
#2 /path/to/webpage/cache/twig/f0/f06ae2f5b2803384507c810b0c39e41f628ed5ee8ccf6e87cb7440dcf1bca162.php(167): Twig_Template->displayBlock('page', Array, Array)
#3 /path/to/webpage/vendor/twig/twig/lib/Twig/Template.php(215): __TwigTemplate_971c1000ff0ad781c34e7a9b752181f10b47bed1688dcc756b57404e69ec239d->block_body(Array, Array)
#4 /path/to/webpage/cache/twig/f0/f06ae2f5b2803384507c810b0c39e41f628ed5ee8ccf6e87cb7440dcf1bca162.php(52): Twig_Template->displayBlock('body', Array, Array)
#5 /path/to/webpage/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_971c1000ff0ad781c34e7a9b752181f10b47bed1688dcc756b57404e69ec239d->doDisplay(Array, Array)
#6 /path/to/webpage/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array)
#7 /path/to/webpage/cache/twig/52/52a293b76e3e1a35b7010558e8703f937ace127c0d6fb42f92fde76fa4cac9af.php(23): Twig_Template->display(Array, Array)
#8 /path/to/webpage/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_337c271fe17c8eab85e22cb1998aa6ccac01f465625ed066457774036a2d3832->doDisplay(Array, Array)
#9 /path/to/webpage/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array)
#10 /path/to/webpage/cache/twig/41/41a3a64d6dafc4766713a9c5e5e51a365e4d86a768aca91f39d0b86e05d48212.php(30): Twig_Template->display(Array, Array)
#11 /path/to/webpage/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_815a98182db53e218ad21e9f09208b0c8bf3171108aa027c44130ba467dc70cf->doDisplay(Array, Array)
#12 /path/to/webpage/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array)
#13 /path/to/webpage/vendor/twig/twig/lib/Twig/Template.php(411): Twig_Template->display(Array)
#14 /path/to/webpage/vendor/twig/twig/lib/Twig/Environment.php(363): Twig_Template->render(Array)
#15 /path/to/webpage/system/src/Grav/Common/Twig/Twig.php(349): Twig_Environment->render('preview.html.tw...', Array)
#16 /path/to/webpage/system/src/Grav/Common/Service/OutputServiceProvider.php(27): Grav\Common\Twig\Twig->processSite('html')
#17 /path/to/webpage/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\OutputServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav))
#18 /path/to/webpage/system/src/Grav/Common/Processors/RenderProcessor.php(19): Pimple\Container->offsetGet('output')
#19 /path/to/webpage/system/src/Grav/Common/Grav.php(132): Grav\Common\Processors\RenderProcessor->process()
#20 /path/to/webpage/system/src/Grav/Common/Grav.php(374): Grav\Common\Grav->Grav\Common\{closure}()
#21 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('render', 'Render', Object(Closure))
#22 /path/to/webpage/system/src/Grav/Common/Grav.php(350): call_user_func_array(Object(Closure), Array)
#23 /path/to/webpage/system/src/Grav/Common/Grav.php(133): Grav\Common\Grav->__call('measureTime', Array)
#24 /path/to/webpage/index.php(52): Grav\Common\Grav->process()
#25 {main} [] []
```

I've tried to clean the cache using the admin panel and also by cleaning manually the cache folder. The web page is running under Debian Linux (Stretch) using Apache 2.4 and PHP 7.0.

Greeting Tobias

**Comment by rhukster** [comment]
Fixed in develop branch of admin
