### ISSUE TITLE
Fatal error during update : CacheCommand not found

### ISSUE THREAD

**Issue by Romarain** [getgrav/grav#2583]
Trying to self-upgrade from a 1.6.0-rc.4, I have this error during the process : 

```
Preparing to upgrade to v1.7.0-beta.4..
  |- Downloading upgrade [4.65M]...   100%
  |- Installing upgrade...    ok
  '- Success!

PHP Fatal error:  Uncaught Error: Class 'Grav\Console\Cli\CacheCommand' not found in D:\Travail\Programmation\Web\Projets_pro\Resonnances\www\system\src\Grav\Console\ConsoleTrait.php:110
Stack trace:
#0 D:\Travail\Programmation\Web\Projets_pro\Resonnances\www\system\src\Grav\Console\Gpm\SelfupgradeCommand.php(176): Grav\Console\ConsoleCommand->clearCache(Array)
#1 D:\Travail\Programmation\Web\Projets_pro\Resonnances\www\system\src\Grav\Console\ConsoleCommand.php(30): Grav\Console\Gpm\SelfupgradeCommand->serve()
#2 D:\Travail\Programmation\Web\Projets_pro\Resonnances\www\vendor\symfony\console\Command\Command.php(255): Grav\Console\ConsoleCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 D:\Travail\Programmation\Web\Projets_pro\Resonnances\www\vendor\symfony\console\Application.php(908): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 D:\Travail in D:\Travail\Programmation\Web\Projets_pro\Resonnances\www\system\src\Grav\Console\ConsoleTrait.php on line 110

Fatal error: Uncaught Error: Class 'Grav\Console\Cli\CacheCommand' not found in D:\Travail\Programmation\Web\Projets_pro\Resonnances\www\system\src\Grav\Console\ConsoleTrait.php:110
Stack trace:
#0 D:\Travail\Programmation\Web\Projets_pro\Resonnances\www\system\src\Grav\Console\Gpm\SelfupgradeCommand.php(176): Grav\Console\ConsoleCommand->clearCache(Array)
#1 D:\Travail\Programmation\Web\Projets_pro\Resonnances\www\system\src\Grav\Console\ConsoleCommand.php(30): Grav\Console\Gpm\SelfupgradeCommand->serve()
#2 D:\Travail\Programmation\Web\Projets_pro\Resonnances\www\vendor\symfony\console\Command\Command.php(255): Grav\Console\ConsoleCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 D:\Travail\Programmation\Web\Projets_pro\Resonnances\www\vendor\symfony\console\Application.php(908): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 D:\Travail in D:\Travail\Programmation\Web\Projets_pro\Resonnances\www\system\src\Grav\Console\ConsoleTrait.php on line 110
```

**Comment by rhukster** [comment]
Unfortunately, 1.6.0-rc.4 was broken in this regard.  It should upgrade fine from 1.6.x release version.
