### ISSUE TITLE
Grav v1.7.0-beta.6 Server error when accessing Admin Panel - Dashboard

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#2653]
After upgrading to the latest 1.7 beta (6, from 5) in my Open Course Hub skeleton, going to the Admin Panel - Dashboard generates this error:

`0 - An exception has been thrown during the rendering of a template ("Identifier "flex_objects" is not defined.").`

Going to other Admin Panel pages seems to be a-ok.

Please let me know if other info would be helpful.

Thanks,
Paul

ps - here is the Grav log entry:

```
[2019-08-29 16:46:17] grav.CRITICAL: An exception has been thrown during the rendering of a template ("Identifier "flex_objects" is not defined."). - Trace: #0 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array) #1 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/cache/twig/cb/cbeeab8f3a4a38e66e0705255818c4993f42892366da5ac69cd5597a520be3ab.php(239): Twig\Template->display(Array) #2 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/vendor/twig/twig/src/Template.php(216): __TwigTemplate_fda8631372aa9e1deccf23b3197554147c1210f6e2c8c0b44478b6a4bbc37113->block_content(Array, Array) #3 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/cache/twig/d8/d85b7520f8dd32486d4e9b6d3d4fdbd5ba1341243f1bef9b505c88caeb1ffc5c.php(361): Twig\Template->displayBlock('content', Array, Array) #4 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/vendor/twig/twig/src/Template.php(216): __TwigTemplate_b3f16cf6a2ce0c6ddc7a7ee538270e31e9b3c1dd80bad4d5044f0e61d098fa39->block_content_wrapper(Array, Array) #5 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/cache/twig/d8/d85b7520f8dd32486d4e9b6d3d4fdbd5ba1341243f1bef9b505c88caeb1ffc5c.php(287): Twig\Template->displayBlock('content_wrapper', Array, Array) #6 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/vendor/twig/twig/src/Template.php(216): __TwigTemplate_b3f16cf6a2ce0c6ddc7a7ee538270e31e9b3c1dd80bad4d5044f0e61d098fa39->block_page(Array, Array) #7 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/cache/twig/d8/d85b7520f8dd32486d4e9b6d3d4fdbd5ba1341243f1bef9b505c88caeb1ffc5c.php(241): Twig\Template->displayBlock('page', Array, Array) #8 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/vendor/twig/twig/src/Template.php(216): __TwigTemplate_b3f16cf6a2ce0c6ddc7a7ee538270e31e9b3c1dd80bad4d5044f0e61d098fa39->block_body(Array, Array) #9 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/cache/twig/d8/d85b7520f8dd32486d4e9b6d3d4fdbd5ba1341243f1bef9b505c88caeb1ffc5c.php(69): Twig\Template->displayBlock('body', Array, Array) #10 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/vendor/twig/twig/src/Template.php(455): __TwigTemplate_b3f16cf6a2ce0c6ddc7a7ee538270e31e9b3c1dd80bad4d5044f0e61d098fa39->doDisplay(Array, Array) #11 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array) #12 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/cache/twig/ad/ad09e7a5e9b0d7f40866d451262928cbef65a1c766d79b92eb7ee748143fd2a1.php(37): Twig\Template->display(Array, Array) #13 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/vendor/twig/twig/src/Template.php(455): __TwigTemplate_c4eb2f42bf55233c63498f28e28b85fb44adfde46b9d1c049cfa4147c996f191->doDisplay(Array, Array) #14 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array) #15 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/cache/twig/cb/cbeeab8f3a4a38e66e0705255818c4993f42892366da5ac69cd5597a520be3ab.php(46): Twig\Template->display(Array, Array) #16 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/vendor/twig/twig/src/Template.php(455): __TwigTemplate_fda8631372aa9e1deccf23b3197554147c1210f6e2c8c0b44478b6a4bbc37113->doDisplay(Array, Array) #17 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array) #18 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/vendor/twig/twig/src/Template.php(434): Twig\Template->display(Array) #19 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/vendor/twig/twig/src/TemplateWrapper.php(47): Twig\Template->render(Array, Array) #20 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/vendor/twig/twig/src/Environment.php(384): Twig\TemplateWrapper->render(Array) #21 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Twig/Twig.php(409): Twig\Environment->render('dashboard.html....', Array) #22 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Service/OutputServiceProvider.php(28): Grav\Common\Twig\Twig->processSite('html') #23 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\OutputServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #24 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Processors/RenderProcessor.php(28): Pimple\Container->offsetGet('output') #25 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\RenderProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #26 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #27 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Processors/DebuggerAssetsProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #28 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\DebuggerAssetsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #29 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #30 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Processors/PagesProcessor.php(69): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #31 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\PagesProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #32 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #33 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Processors/TwigProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #34 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\TwigProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #35 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #36 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Processors/AssetsProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #37 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\AssetsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #38 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #39 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Processors/SchedulerProcessor.php(29): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #40 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\SchedulerProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #41 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #42 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Processors/BackupsProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #43 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\BackupsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #44 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #45 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Processors/TasksProcessor.php(59): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #46 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\TasksProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #47 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #48 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/user/plugins/admin/classes/plugin/Router.php(51): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #49 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Plugin\Admin\Router->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #50 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #51 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Processors/RequestProcessor.php(52): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #52 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\RequestProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #53 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #54 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Processors/ThemesProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #55 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ThemesProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #56 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #57 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Processors/PluginsProcessor.php(30): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #58 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\PluginsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #59 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #60 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Processors/InitializeProcessor.php(66): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #61 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Debugger.php(533): Grav\Common\Processors\InitializeProcessor->Grav\Common\Processors\{closure}() #62 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Processors/InitializeProcessor.php(67): Grav\Common\Debugger->profile(Object(Closure)) #63 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\InitializeProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #64 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #65 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/system/src/Grav/Common/Grav.php(224): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #66 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/grav-17-skeleton-open-matter-course-hub-site/index.php(56): Grav\Common\Grav->process() #67 {main} [] []
```

**Comment by rhukster** [comment]
It seems we have a `flex-objects` plugin assumption in the Grav Admin... I'm sure @mahagr will take a look.

**Comment by rhukster** [comment]
For now i've removed the builds from the release.  It will still show up, but you won't be able to update.

**Comment by mahagr** [comment]
Whoops, sorry about the mistake. The fix is here: https://github.com/getgrav/grav-plugin-admin/commit/0e236310381b6f6023e1d5b5df4c2a4178fb31e6 in case if you want to test the build.

**Comment by paulhibbitts** [comment]
Thanks very much @mahagr , just tested the fix and the Admin Dashboard is accessible again👍

**Comment by rhukster** [comment]
Will get a release out today.

**Comment by SteveBaumann** [comment]
Looks like the Admin Panel 1.10.0 beta 7 doesn't crash anymore, but one of the other side effects still remains. 
The left sidebar in the Dashboard still repeats items: 

![grav-admin-panel_1-10-0-beta-7_repeat-items](https://user-images.githubusercontent.com/11002590/64049643-55cbdf00-cb2a-11e9-99f7-14a2997356b0.png)

You'll notice the first 3 items are repeated, and then Plugins and the 2 following items are also repeated.

**Comment by rhukster** [comment]
doh!!

**Comment by rhukster** [comment]
Created a new issue for this.

**Comment by mahagr** [comment]
Is there a template override as the menu file was updated with all the fixed menu items removed?
