### ISSUE TITLE
Regression after upgrade to 1.6.19 in a docker deployment => content wiped out when adding a new page

### ISSUE THREAD

**Issue by nsteinmetz** [getgrav/grav#2761]
Hi there,

I upgraded from 1.6.16 to 1.16.19, I deployed grav in a docker container and I have this error since - I think the first one can be ignore but the latter is the crucial one as it leads to all content of the site to be wiped out

```
[2019-12-13 11:02:04] grav.CRITICAL: SplFileInfo::getMTime(): stat failed for /var/www/html/user/pages/07.galerie/animation-laser/2007/2007-09-29-ml - Trace: #0 /var/www/html/system/src/Grav/Common/Filesystem/Folder.php(109): SplFileInfo->getMTime() #1 /var/www/html/system/src/Grav/Common/Page/Pages.php(977): Grav\Common\Filesystem\Folder::hashAllFiles('/var/www/html/u...') #2 /var/www/html/system/src/Grav/Common/Page/Pages.php(261): Grav\Common\Page\Pages->buildPages() #3 /var/www/html/system/src/Grav/Common/Processors/PagesProcessor.php(30): Grav\Common\Page\Pages->init() #4 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\PagesProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #5 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #6 /var/www/html/system/src/Grav/Common/Processors/TwigProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #7 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\TwigProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #8 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #9 /var/www/html/system/src/Grav/Common/Processors/AssetsProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #10 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\AssetsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #11 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #12 /var/www/html/system/src/Grav/Common/Processors/SchedulerProcessor.php(29): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #13 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\SchedulerProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #14 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #15 /var/www/html/system/src/Grav/Common/Processors/BackupsProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #16 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\BackupsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #17 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #18 /var/www/html/system/src/Grav/Common/Processors/TasksProcessor.php(59): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #19 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\TasksProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #20 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #21 /var/www/html/system/src/Grav/Common/Processors/RequestProcessor.php(52): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #22 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\RequestProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #23 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #24 /var/www/html/system/src/Grav/Common/Processors/ThemesProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #25 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ThemesProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #26 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #27 /var/www/html/system/src/Grav/Common/Processors/PluginsProcessor.php(30): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #28 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\PluginsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #29 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #30 /var/www/html/system/src/Grav/Common/Processors/InitializeProcessor.php(78): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #31 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\InitializeProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #32 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #33 /var/www/html/system/src/Grav/Common/Processors/DebuggerProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #34 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\DebuggerProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #35 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #36 /var/www/html/system/src/Grav/Common/Processors/ErrorsProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #37 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ErrorsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #38 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #39 /var/www/html/system/src/Grav/Common/Processors/LoggerProcessor.php(48): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #40 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\LoggerProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #41 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #42 /var/www/html/system/src/Grav/Common/Processors/ConfigurationProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #43 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ConfigurationProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #44 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #45 /var/www/html/system/src/Grav/Common/Grav.php(249): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #46 /var/www/html/index.php(53): Grav\Common\Grav->process() #47 {main} [] []

[2019-12-13 11:02:04] grav.CRITICAL: rmdir(/var/www/html/user/pages): Device or resource busy - Trace: #0 /var/www/html/system/src/Grav/Common/Debugger.php(352): Whoops\Run->handleError(2, 'rmdir(/var/www/...', '/var/www/html/u...', 136) #1 [internal function]: Grav\Common\Debugger->deprecatedErrorHandler(2, 'rmdir(/var/www/...', '/var/www/html/u...', 136, Array) #2 /var/www/html/user/plugins/events/classes/iCalendarProcessor.php(136): rmdir('/var/www/html/u...') #3 /var/www/html/user/plugins/events/classes/iCalendarProcessor.php(74): Events\iCalendarProcessor->rmdir_recursive('/var/www/html/u...') #4 /var/www/html/user/plugins/events/events.php(358): Events\iCalendarProcessor->process() #5 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Grav\Plugin\EventsPlugin->onAdminAfterSave(Object(RocketTheme\Toolbox\Event\Event), 'onAdminAfterSav...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #6 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onAdminAfterSav...', Object(RocketTheme\Toolbox\Event\Event)) #7 /var/www/html/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onAdminAfterSav...', Object(RocketTheme\Toolbox\Event\Event)) #8 /var/www/html/system/src/Grav/Common/Grav.php(377): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onAdminAfterSav...', Object(RocketTheme\Toolbox\Event\Event)) #9 /var/www/html/user/plugins/admin/classes/admincontroller.php(658): Grav\Common\Grav->fireEvent('onAdminAfterSav...', Object(RocketTheme\Toolbox\Event\Event)) #10 /var/www/html/user/plugins/admin/classes/admincontroller.php(564): Grav\Plugin\Admin\AdminController->taskSavePage() #11 /var/www/html/user/plugins/admin/classes/adminbasecontroller.php(110): Grav\Plugin\Admin\AdminController->taskSave() #12 /var/www/html/user/plugins/admin/admin.php(812): Grav\Plugin\Admin\AdminBaseController->execute() #13 /var/www/html/user/plugins/admin/admin.php(437): Grav\Plugin\AdminPlugin->initializeController('save', Array) #14 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Grav\Plugin\AdminPlugin->onPagesInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #15 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #16 /var/www/html/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #17 /var/www/html/system/src/Grav/Common/Grav.php(377): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #18 /var/www/html/system/src/Grav/Common/Processors/PagesProcessor.php(31): Grav\Common\Grav->fireEvent('onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #19 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\PagesProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #20 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #21 /var/www/html/system/src/Grav/Common/Processors/TwigProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #22 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\TwigProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #23 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #24 /var/www/html/system/src/Grav/Common/Processors/AssetsProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #25 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\AssetsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #26 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #27 /var/www/html/system/src/Grav/Common/Processors/SchedulerProcessor.php(29): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #28 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\SchedulerProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #29 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #30 /var/www/html/system/src/Grav/Common/Processors/BackupsProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #31 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\BackupsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #32 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #33 /var/www/html/system/src/Grav/Common/Processors/TasksProcessor.php(59): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #34 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\TasksProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #35 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #36 /var/www/html/system/src/Grav/Common/Processors/RequestProcessor.php(52): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #37 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\RequestProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #38 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #39 /var/www/html/system/src/Grav/Common/Processors/ThemesProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #40 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ThemesProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #41 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #42 /var/www/html/system/src/Grav/Common/Processors/PluginsProcessor.php(30): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #43 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\PluginsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #44 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #45 /var/www/html/system/src/Grav/Common/Processors/InitializeProcessor.php(78): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #46 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\InitializeProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #47 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #48 /var/www/html/system/src/Grav/Common/Processors/DebuggerProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #49 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\DebuggerProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #50 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #51 /var/www/html/system/src/Grav/Common/Processors/ErrorsProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #52 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ErrorsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #53 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #54 /var/www/html/system/src/Grav/Common/Processors/LoggerProcessor.php(48): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #55 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\LoggerProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #56 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #57 /var/www/html/system/src/Grav/Common/Processors/ConfigurationProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #58 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ConfigurationProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #59 /var/www/html/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #60 /var/www/html/system/src/Grav/Common/Grav.php(249): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #61 /var/www/html/index.php(53): Grav\Common\Grav->process() #62 {main} [] []
```

my docker-compose file is as below:

```
version: '3'
services:
    web:
      image: grav:1.6.19-cvsq
      depends_on:
        - redis
      labels:
        - "traefik.http.routers.cvsq.rule=Host(`www.cvsq.fr`) || Host(`cvsq.fr`)"
        - "traefik.http.routers.cvsq.entrypoints=http"
        - "traefik.http.routers.cvsq.middlewares=cvsqToHttps"
        - "traefik.http.routers.cvsqs.rule=Host(`www.cvsq.fr`) || Host(`cvsq.fr`)"
        - "traefik.http.routers.cvsqs.entrypoints=https"
        - "traefik.http.routers.cvsqs.tls=true"
        - "traefik.http.middlewares.cvsqToHttps.redirectscheme.scheme=https"
        - "traefik.http.services.cvsq.loadbalancer.server.port=80"
        - "traefik.http.services.cvsq.loadbalancer.server.scheme=http"    
        - "traefik.docker.network=cvsq-www"
      restart: always
      volumes:
        - /srv/www/cvsq.fr/www/assets:/var/www/html/assets
        - /srv/www/cvsq.fr/www/backup:/var/www/html/backup
        - /srv/www/cvsq.fr/www/cache:/var/www/html/cache
        - /srv/www/cvsq.fr/www/images:/var/www/html/images
        - /srv/www/cvsq.fr/www/logs:/var/www/html/logs
        - /srv/www/cvsq.fr/www/user/accounts:/var/www/html/user/accounts
        - /srv/www/cvsq.fr/www/user/config:/var/www/html/user/config
        - /srv/www/cvsq.fr/www/user/data:/var/www/html/user/data
        - /srv/www/cvsq.fr/www/user/pages:/var/www/html/user/pages
        - /srv/www/cvsq.fr/www/user/themes/cvsq:/var/www/html/user/themes/cvsq
        - /srv/www/cvsq.fr/www/tmp:/var/www/html/tmp
    redis:
      image: redis:alpine
      labels:
        - "traefik.enable=false"
      restart: always
```

It worked well so far - issue happend after the upgrade from 1.6.16 to 1.6.19

For the `Dockerfile` that are used

image `grav:1.6.19`

```
FROM php:7-apache
ARG GRAV_VERSION=1.6.19
ADD https://github.com/getgrav/grav/releases/download/${GRAV_VERSION}/grav-admin-v${GRAV_VERSION}.zip /tmp/grav-admin-v${GRAV_VERSION}.zip

COPY apache_security.conf /etc/apache2/conf-available/apache_security.conf
COPY apache_csp.conf /etc/apache2/conf-available/apache_csp.conf

COPY uploads.conf /usr/local/etc/php-fpm.d/uploads.conf
COPY security.conf /usr/local/etc/php-fpm.d/security.conf
COPY memory.conf /usr/local/etc/php-fpm.d/memory.conf

RUN apt update -y -q \
  && apt install -y unzip \
    libfreetype6-dev libjpeg62-turbo-dev libpng-dev \
    libzip4 libzip-dev \
    libyaml-0-2 libyaml-dev \
  && unzip /tmp/grav-admin-v${GRAV_VERSION}.zip -d /tmp/ \
  && mv /tmp/grav-admin/* /var/www/html/ \
  && mv /tmp/grav-admin/.htaccess /var/www/html/ \
  && chown www-data:www-data -R /var/www/html \
  && docker-php-ext-configure gd --with-freetype --with-jpeg \
  && docker-php-ext-install zip gd opcache \
  && pecl install redis yaml apcu \
  && docker-php-ext-enable redis yaml apcu \
  && rm -rf /var/cache/apt/lists/* \
  && rm -rf /tmp/grav-admin-v${GRAV_VERSION}.zip \
  && cd /var/www/html && ./bin/gpm update --no-interaction \
  && ./bin/gpm install -y --no-interaction quark \
  && a2enmod rewrite \
  && a2enmod headers \
  && a2disconf security \
  && a2enconf apache_csp \
  && a2enconf apache_security
```

and for the customisation for this site :

Image `grav:1.6.19-cvsq`:

```
FROM grav:1.6.19
COPY apache_csp.conf /etc/apache2/conf-available/apache_csp.conf
COPY apache_expires.conf /etc/apache2/conf-available/apache_expires.conf
COPY apache_headers.conf /etc/apache2/conf-available/apache_headers.conf
WORKDIR /var/www/html
RUN ./bin/gpm install -n -y datetools \
  && ./bin/gpm install -n -y events \
  && ./bin/gpm install -n -y featherlight \
  && ./bin/gpm install -n -y quick-tray-links \
  && ./bin/gpm install -n -y breadcrumbs \
  && ./bin/gpm install -n -y data-manager \
  && ./bin/gpm install -n -y count-views \
  && cp webserver-configs/htaccess.txt .htaccess \
  && a2enmod expires \
  && a2enconf apache_expires \
  && a2enconf apache_headers
```

**Comment by nsteinmetz** [comment]
Editing a page lead also to content being wiped out.

**Comment by nsteinmetz** [comment]
Hmm seems linked with the event plugin:

```
var/www/html/user/plugins/events/classes/iCalendarProcessor.php

         *
         * @since  1.1.0  Initial Release
         * @return void
         */
        private function rmdir_recursive( $dir )
        {
            if (is_dir("$dir")) {
                foreach(scandir($dir) as $file) {
                    if ('.' === $file || '..' === $file)
                        continue;
     
                    if (is_dir("$dir/$file")) {
                        $this->rmdir_recursive("$dir/$file");
                    }
                    else {
                        unlink("$dir/$file");
                    }
                }
     
                rmdir($dir);
            }
        }
     
        /**
         * Creates a new page for a given event.
         *
         * Parses a given event and creates the accoring folder and event.md file.
         *
         * Currently ignores rrules as the used ics-parser doesn't support them
         * correctly. Instead, it prefixes each event folder with the month and day
         * of the according event.
         *
         * @since  1.1.0  Initial Release
         * @return void
         */
        private function create_page( $ical_path, $event, &$files )
        {
            $file_name = '/event.md';
     
            // get the event information

Arguments

    "rmdir(/var/www/html/user/pages): Device or resource busy"

```

**Comment by nsteinmetz** [comment]
Just sent a mail to the author of the plugins - let's see what happens...

**Comment by nsteinmetz** [comment]
Ok so in the plugins config, the `Events subpage` section must be correctly defined. When set to the correct directory it works as expected.
