### ISSUE TITLE
Grav 1.6.19 on PHP 7.4.1 is broken (again?)

### ISSUE THREAD

**Issue by spectroman** [getgrav/grav#2777]
I have tried Grav on 7.4 before and I realized it was broken in several places. I fixed a couple of those but more kept appearing in different places, I decided to wait for an official update.

According to https://github.com/getgrav/grav/issues/2750 this updated supposedly have fixed some of the problems I have seen before. But as I am testing it now, I get again:

```Server Error
Sorry, something went terribly wrong!

E_NOTICE - Trying to access array offset on value of type null
For further details please review your logs/ folder, or enable displaying of errors in your system configuration.
```

And at the log, there is a non polite message:

`Trying to access array offset on value of type null - Trace: #0 /data/webserver/www-gravtest-com/system/src/Grav/Common/Debugger.php(352): Whoops\Run->handleError() #1 /data/webserver/www-gravtest-com/user/plugins/comments/comments.php(350): Grav\Common\Debugger->deprecatedErrorHandler() #2 /data/webserver/www-gravtest-com/user/plugins/comments/comments.php(77): Grav\Plugin\CommentsPlugin->fetchComments() #3 /data/webserver/www-gravtest-com/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Grav\Plugin\CommentsPlugin->onTwigSiteVariables() #4 /data/webserver/www-gravtest-com/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() #5 /data/webserver/www-gravtest-com/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch() #6 /data/webserver/www-gravtest-com/system/src/Grav/Common/Grav.php(377): RocketTheme\Toolbox\Event\EventDispatcher->dispatch() #7 /data/webserver/www-gravtest-com/system/src/Grav/Common/Twig/Twig.php(363): Grav\Common\Grav->fireEvent() #8 /data/webserver/www-gravtest-com/system/src/Grav/Common/Service/OutputServiceProvider.php(28): Grav\Common\Twig\Twig->processSite() #9 /data/webserver/www-gravtest-com/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\OutputServiceProvider->Grav\Common\Service\{closure}() #10 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/RenderProcessor.php(28): Pimple\Container->offsetGet() #11 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\RenderProcessor->process() #12 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() #13 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/DebuggerAssetsProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle() #14 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\DebuggerAssetsProcessor->process() #15 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() #16 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/PagesProcessor.php(69): Grav\Framework\RequestHandler\RequestHandler->handle() #17 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\PagesProcessor->process() #18 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() #19 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/TwigProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle() #20 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\TwigProcessor->process() #21 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() #22 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/AssetsProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle() #23 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\AssetsProcessor->process() #24 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() #25 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/SchedulerProcessor.php(29): Grav\Framework\RequestHandler\RequestHandler->handle() #26 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\SchedulerProcessor->process() #27 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() #28 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/BackupsProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle() #29 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\BackupsProcessor->process() #30 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() #31 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/TasksProcessor.php(59): Grav\Framework\RequestHandler\RequestHandler->handle() #32 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\TasksProcessor->process() #33 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() #34 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/RequestProcessor.php(52): Grav\Framework\RequestHandler\RequestHandler->handle() #35 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\RequestProcessor->process() #36 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() #37 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/ThemesProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle() #38 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ThemesProcessor->process() #39 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() #40 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/PluginsProcessor.php(30): Grav\Framework\RequestHandler\RequestHandler->handle() #41 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\PluginsProcessor->process() #42 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() #43 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/InitializeProcessor.php(78): Grav\Framework\RequestHandler\RequestHandler->handle() #44 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\InitializeProcessor->process() #45 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() #46 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/DebuggerProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle() #47 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\DebuggerProcessor->process() #48 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() #49 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/ErrorsProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle() #50 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ErrorsProcessor->process() #51 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() #52 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/LoggerProcessor.php(48): Grav\Framework\RequestHandler\RequestHandler->handle() #53 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\LoggerProcessor->process() #54 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() #55 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/ConfigurationProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle() #56 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ConfigurationProcessor->process() #57 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() #58 /data/webserver/www-gravtest-com/system/src/Grav/Common/Grav.php(249): Grav\Framework\RequestHandler\RequestHandler->handle() #59 /data/webserver/www-gravtest-com/index.php(53): Grav\Common\Grav->process() #60 {main}
`

I kinda feels like, more of the same?

More details:

```php --version
PHP 7.4.1 (cli) (built: Dec 18 2019 12:59:28) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

And:

```httpd -V
Server version: Apache/2.4.41 (Unix)
Server built:   Aug 13 2019 22:44:41
Server's Module Magic Number: 20120211:88
Server loaded:  APR 1.7.0, APR-UTIL 1.6.1
Compiled using: APR 1.7.0, APR-UTIL 1.6.1
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_PROC_PTHREAD_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/httpd"
 -D SUEXEC_BIN="/usr/bin/suexec"
 -D DEFAULT_PIDLOG="/run/httpd/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="conf/mime.types"
 -D SERVER_CONFIG_FILE="conf/httpd.conf"
```

Running on Arch Linux.

**Comment by rhukster** [comment]
Based on the stacktrace the error is in the "comments" plugin.  I'm moving the issue there.
