### ISSUE TITLE
Grav 1.7 RC.5 Error after upgrading

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#2811]
After upgrading from 1.6.19 -> RC5 the following error is shown on the Pages panel:

<img width="1200" alt="2020-02-03_12-06-56" src="https://user-images.githubusercontent.com/1812771/73689420-08c4d980-4683-11ea-9b00-2027375f2ee2.png">

Please let me know if any additional info is helpful.

Thanks very much,
Paul

ps - here is the log:
```
[2020-02-03 13:32:34] grav.DEBUG: Flex: User index updated, 1 objects (1 added, 0 updated, 0 removed). [] []
[2020-02-03 13:32:42] grav.CRITICAL: Call to a member function parents() on string - Trace: #0 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/rockettheme/toolbox/Blueprints/src/BlueprintSchema.php(81): RocketTheme\Toolbox\Blueprints\BlueprintSchema->dynamicData(Array, 'options', Array) #1 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Common/Data/Blueprint.php(290): RocketTheme\Toolbox\Blueprints\BlueprintSchema->init() #2 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Common/Data/Blueprint.php(261): Grav\Common\Data\Blueprint->initInternals() #3 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(702): Grav\Common\Data\Blueprint->schema() #4 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/cache/twig/a8/a87cf1b2d3234c6b6a4481202585eb2ed3c881475c7fb2f6807da76858dc0b8d.php(47): Twig\Template->getAttribute(Object(Grav\Common\Data\Blueprint), 'schema', Array, 'any', false, true) #5 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(455): __TwigTemplate_cec3144dba69ae1dd4a2751674693bd0636b36fd5cf259aaf978132127a60fa3->doDisplay(Array, Array) #6 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array) #7 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/cache/twig/4b/4bb1f5a1578beada1162c2fc878d1a07b09a8249934c147b219b99a43fc9cfd8.php(38): Twig\Template->display(Array, Array) #8 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(455): __TwigTemplate_caf17809dc926429736259e33ea5e2e55cc76f01d38123c60e24a692899731f2->doDisplay(Array, Array) #9 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array) #10 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/cache/twig/ca/ca25955cee734a2cbaca983685fe984f3eba49bcd23b54937095d98b17561de3.php(74): Twig\Template->display(Array) #11 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(455): __TwigTemplate_13d8e2c35b23ebbb85a80eb8964fc962d4274b4abadc534e3f4294c4a28b85c0->doDisplay(Array, Array) #12 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array) #13 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/cache/twig/f7/f77205efd78a4525a8cfbd6e1f15986a6abf65ba5b5298d08a04a712c8346db1.php(260): Twig\Template->display(Array) #14 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(216): __TwigTemplate_8bdffeef0767bb41a962d235977422bd77defd64cd262ff7486a05ddfbc83cd5->block_directory(Array, Array) #15 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/cache/twig/f7/f77205efd78a4525a8cfbd6e1f15986a6abf65ba5b5298d08a04a712c8346db1.php(42): Twig\Template->displayBlock('directory', Array, Array) #16 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(455): __TwigTemplate_8bdffeef0767bb41a962d235977422bd77defd64cd262ff7486a05ddfbc83cd5->doDisplay(Array, Array) #17 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array) #18 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/cache/twig/e4/e44a4340e2c21c9557de7ba5d6762adffe9a4587a2e16d43e4baea39745b4117.php(131): Twig\Template->display(Array) #19 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(216): __TwigTemplate_57931085c58d3c824d00068afebcfd62669f3ebaeda51fa610dee56d753f2345->block_content_list(Array, Array) #20 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/cache/twig/de/dec4042e2fc4a6a896c64b269c0ab68f020ca9f2f10f96f7ed0ef4f94a08ffaf.php(213): Twig\Template->displayBlock('content_list', Array, Array) #21 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(216): __TwigTemplate_bae291886438cfd5ea53089675c2099128e81d877e0ae79de1009841dda13dd7->block_content(Array, Array) #22 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/cache/twig/14/1443c51f06e2e0c5f885d6d37dcfc09eaced146d90c49a27cdd74cd82ca28c4a.php(383): Twig\Template->displayBlock('content', Array, Array) #23 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(216): __TwigTemplate_49c12bc779af48a946d2b01dfa45d8bc616e0b376b36f2b4f319d38f0d804a60->block_content_wrapper(Array, Array) #24 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/cache/twig/14/1443c51f06e2e0c5f885d6d37dcfc09eaced146d90c49a27cdd74cd82ca28c4a.php(309): Twig\Template->displayBlock('content_wrapper', Array, Array) #25 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(216): __TwigTemplate_49c12bc779af48a946d2b01dfa45d8bc616e0b376b36f2b4f319d38f0d804a60->block_page(Array, Array) #26 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/cache/twig/14/1443c51f06e2e0c5f885d6d37dcfc09eaced146d90c49a27cdd74cd82ca28c4a.php(247): Twig\Template->displayBlock('page', Array, Array) #27 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(216): __TwigTemplate_49c12bc779af48a946d2b01dfa45d8bc616e0b376b36f2b4f319d38f0d804a60->block_body(Array, Array) #28 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(236): Twig\Template->displayBlock('body', Array, Array, false) #29 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(177): Twig\Template->displayBlock('body', Array, Array, false) #30 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/cache/twig/de/dec4042e2fc4a6a896c64b269c0ab68f020ca9f2f10f96f7ed0ef4f94a08ffaf.php(171): Twig\Template->displayParentBlock('body', Array, Array) #31 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(216): __TwigTemplate_bae291886438cfd5ea53089675c2099128e81d877e0ae79de1009841dda13dd7->block_body(Array, Array) #32 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/cache/twig/14/1443c51f06e2e0c5f885d6d37dcfc09eaced146d90c49a27cdd74cd82ca28c4a.php(70): Twig\Template->displayBlock('body', Array, Array) #33 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(455): __TwigTemplate_49c12bc779af48a946d2b01dfa45d8bc616e0b376b36f2b4f319d38f0d804a60->doDisplay(Array, Array) #34 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array) #35 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/cache/twig/8a/8a414348cedbeba85f179e87eb884e8498c30b26ddfd48419dfccef1a78d6fcf.php(37): Twig\Template->display(Array, Array) #36 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(455): __TwigTemplate_eb82889db6a1c0b0699ad4f6ebcd97ac21725344db769b394a81c9d88c19fb8f->doDisplay(Array, Array) #37 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array) #38 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/cache/twig/de/dec4042e2fc4a6a896c64b269c0ab68f020ca9f2f10f96f7ed0ef4f94a08ffaf.php(97): Twig\Template->display(Array, Array) #39 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(455): __TwigTemplate_bae291886438cfd5ea53089675c2099128e81d877e0ae79de1009841dda13dd7->doDisplay(Array, Array) #40 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array) #41 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/cache/twig/e4/e44a4340e2c21c9557de7ba5d6762adffe9a4587a2e16d43e4baea39745b4117.php(44): Twig\Template->display(Array, Array) #42 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(455): __TwigTemplate_57931085c58d3c824d00068afebcfd62669f3ebaeda51fa610dee56d753f2345->doDisplay(Array, Array) #43 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array) #44 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/cache/twig/75/754c56f58a74f5f6379852fe555cbff26d76e6d2f0ca202d71497ca04a1bcb49.php(64): Twig\Template->display(Array, Array) #45 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(455): __TwigTemplate_a7f801ab48d1c203e17e6d4c48d1637d1e882616124ff05ec5f851352964ddc1->doDisplay(Array, Array) #46 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array) #47 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Template.php(434): Twig\Template->display(Array) #48 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/TemplateWrapper.php(47): Twig\Template->render(Array, Array) #49 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/twig/twig/src/Environment.php(384): Twig\TemplateWrapper->render(Array) #50 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Common/Twig/Twig.php(397): Twig\Environment->render('flex-objects.ht...', Array) #51 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Common/Service/OutputServiceProvider.php(28): Grav\Common\Twig\Twig->processSite('html') #52 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\OutputServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #53 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Common/Processors/RenderProcessor.php(30): Pimple\Container->offsetGet('output') #54 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\RenderProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #55 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #56 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Common/Processors/DebuggerAssetsProcessor.php(29): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #57 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\DebuggerAssetsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #58 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #59 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Common/Processors/PagesProcessor.php(71): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #60 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\PagesProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #61 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #62 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Common/Processors/TwigProcessor.php(29): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #63 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\TwigProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #64 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #65 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Common/Processors/AssetsProcessor.php(30): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #66 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\AssetsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #67 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #68 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Common/Processors/SchedulerProcessor.php(31): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #69 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\SchedulerProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #70 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #71 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Common/Processors/BackupsProcessor.php(30): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #72 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\BackupsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #73 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #74 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Common/Processors/TasksProcessor.php(60): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #75 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\TasksProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #76 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #77 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/user/plugins/admin/classes/plugin/Router.php(51): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #78 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Plugin\Admin\Router->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #79 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #80 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Common/Processors/RequestProcessor.php(54): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #81 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\RequestProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #82 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #83 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Common/Processors/ThemesProcessor.php(29): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #84 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ThemesProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #85 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #86 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Common/Processors/PluginsProcessor.php(33): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #87 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\PluginsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #88 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #89 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Common/Processors/InitializeProcessor.php(76): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #90 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Common/Debugger.php(529): Grav\Common\Processors\InitializeProcessor::Grav\Common\Processors\{closure}() #91 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Common/Processors/InitializeProcessor.php(77): Grav\Common\Debugger->profile(Object(Closure)) #92 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\InitializeProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #93 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #94 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/system/src/Grav/Common/Grav.php(228): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #95 /Users/paulhibbitts/Documents/My Files/GitHub/_TESTS/rc17-flex-grav-skeleton-open-matter-multicourse-hub-site/index.php(56): Grav\Common\Grav->process() #96 {main} [] []
```

**Comment by lufog** [comment]
To fix run: ```php bin\gpm update -y```.

**Comment by paulhibbitts** [comment]
Thanks very much @lufog but when I try that I get a `nothing to update` message and still no luck with the Pages Admin panel.

**Comment by mahagr** [comment]
@paulhibbitts you can fix this by running `composer update --no-dev` in the root folder of the installation. If you don't have composer installed, grav has one built into it as well.

**Comment by paulhibbitts** [comment]
Thanks @mahagr but still getting that error message (I cleared cache too). Maybe I need to wait for the next RC to test the update process?

**Comment by mahagr** [comment]
Oh, you also need to get the latest Grav source.

**Comment by paulhibbitts** [comment]
Thanks @mahagr , for now I will just download a fresh R5 and copy my needed pages/themes/plugins/etc
