### ISSUE TITLE
Double slash in url error

### ISSUE THREAD

**Issue by rjspencer** [getgrav/grav#300]
Love building in Grav. Just launched a site and one of the marketing guys dropped the url into a social tool called Buffer. The url he used included `.com/` notice the slash. Buffer shortened the url before posting it. The shortened url had an extra slash added to it `.com//?utm=`, causing a Fatal Exception error. 

The issue only seems to happen if right after the tld.
Error: `.com//?utm=`
No error `.com/page//?utm=`

[2015-09-04 21:20:48] grav.CRITICAL: Undefined index: path - Trace: #0 /var/www/host/new-www.everspringpartners.com/www/system/src/Grav/Common/Grav.php(432): Whoops\Run->handleError(8, 'Undefined index...', '/var/www/host/n...', 432, Array) #1 /var/www/host/new-www.everspringpartners.com/www/system/src/Grav/Common/Grav.php(129): Grav\Common\Grav->fallbackUrl(NULL, '//?utm_content=...') #2 /var/www/host/new-www.everspringpartners.com/www/vendor/pimple/pimple/src/Pimple/Container.php(112): Grav\Common\Grav::Grav\Common\{closure}(Object(Grav\Common\Grav)) #3 /var/www/host/new-www.everspringpartners.com/www/system/src/Grav/Common/Twig/Twig.php(303): Pimple\Container->offsetGet('page') #4 /var/www/host/new-www.everspringpartners.com/www/system/src/Grav/Common/Grav.php(143): Grav\Common\Twig\Twig->processSite(NULL) #5 /var/www/host/new-www.everspringpartners.com/www/vendor/pimple/pimple/src/Pimple/Container.php(112): Grav\Common\Grav::Grav\Common\{closure}(Object(Grav\Common\Grav)) #6 /var/www/host/new-www.everspringpartners.com/www/system/src/Grav/Common/Grav.php(231): Pimple\Container->offsetGet('output') #7 /var/www/host/new-www.everspringpartners.com/www/index.php(31): Grav\Common\Grav->process() #8 {main} [] []

**Comment by rhukster** [comment]
Quite strange.. i'm not seeing this on any of my local test setups, nor on getgrav.org:

http://getgrav.org//?utm=something

**Comment by rjspencer** [comment]
I can't recreate the error anymore. It must have had something to do with our setup, but I don't know what. We were getting 404s for double slashes directly after the tld, but not later in the url. Fixed that with a `redirects: //: /` in the site.yaml.
