### ISSUE TITLE
Deployment to Vercel / Now fails due Uncaught RuntimeException: Creating directory

### ISSUE THREAD

**Issue by Maybach91** [getgrav/grav#3053]
I [copied](https://github.com/Maybach91/grav/tree/master) the repo and added the missing parts in the `now.json` to run php on vercel (since its not an official runtime anymore). 

Maybe i’m not understanding vercel and the deployment fully, but i copied the content of the root `index.php` to `api/index.php` (since its a requirement to have serverless functions there) and i’m not able to run the website just like on my webserver.

`phpinfo()` is working in my index.php file.

I get the following error when accessing the site:
```error
Fatal error: Uncaught RuntimeException: Creating directory failed for /var/task/php/user/config/security.yaml in /var/task/user/vendor/rockettheme/toolbox/File/src/File.php:325 Stack trace: #0 /var/task/user/system/src/Grav/Common/Config/Setup.php(314): RocketTheme\Toolbox\File\File->save() #1 /var/task/user/system/src/Grav/Common/Config/Setup.php(227): Grav\Common\Config\Setup->check(Object(RocketTheme\Toolbox\ResourceLocator\UniformResourceLocator)) #2 /var/task/user/system/src/Grav/Common/Service/ConfigServiceProvider.php(30): Grav\Common\Config\Setup->init() #3 /var/task/user/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\ConfigServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #4 /var/task/user/system/src/Grav/Common/Grav.php(166): Pimple\Container->offsetGet('setup') #5 /var/task/user/system/src/Grav/Common/Grav.php(492): Grav\Common\Grav->Grav\Common\{closure}() #6 /var/task/user/system/src/Grav/Common/Grav.php(168): Grav\Common\Grav->measureTime('_setup', 'Site Setup' in /var/task/user/system/src/Grav/Common/Config/Setup.php on line 318
```
Maybe this is related to #1912 but since i’m not in the local environment anymore i don’t know how to solve this and where to ask/report it.

The vercel log says it was successful:
```log
08:35:04.355  	Cloning github.com/Maybach91/grav (Branch: master, Commit: 2036111)
08:35:05.260  	Cloning completed in 904ms
08:35:05.261  	Analyzing source code...
08:35:07.872  	Uploading build outputs...
08:35:14.449  	Installing build runtime...
08:35:18.275  	Build runtime installed: 3825.989ms
08:35:18.838  	Looking up build cache...
08:35:19.178  	Build cache found. Downloading...
08:35:19.778  	Build cache downloaded [7.03 MB]: 599.374ms
08:35:20.831  	🐘 Installing Composer deps.
08:35:21.046  	[4.3MiB/0.01s] Loading composer repositories with package information
08:35:21.051  	[4.6MiB/0.01s] Installing dependencies from lock file
08:35:21.067  	[4.9MiB/0.03s] Nothing to install or update
08:35:21.068  	[4.5MiB/0.03s] Generating autoload files
08:35:21.076  	[4.6MiB/0.04s] Memory usage: 4.64MiB (peak: 5.61MiB), time: 0.04s
08:35:21.085  	🐘 Installing Composer deps OK.
08:35:31.319  	Uploading build outputs...
08:35:39.050  	Build completed. Populating build cache...
08:35:41.386  	Uploading build cache [7.03 MB]...
08:35:42.540  	Build cache uploaded: 1154.621ms
08:35:42.549  	Done with "api/index.php"
```

Do i have to run bin/grav install or something on vercel as well? As build function? 

I have commented the following section in my `index.php`
```php
if (PHP_SAPI === 'cli-server') {
    $symfony_server = strpos(getenv('_'), 'symfony') !== false;
    if (!isset($_SERVER['PHP_CLI_ROUTER']) && !$symfony_server) {
       // die("PHP webserver requires a router to run Grav, please use: <pre>php -S {$_SERVER['SERVER_NAME']}:{$_SERVER['SERVER_PORT']} system/router.php</pre>");
    }
}
```

I think, this might the issue. But i have no idea how to solve it.

**Comment by rhukster** [comment]
Never used vercel but if you clone Grav, you will need to do a `bin/grav install` to install the vendor libs as well as the default theme, and some basic plugins.
