### ISSUE TITLE
Error in gpm self-upgrade. Missing ZipArchive

### ISSUE THREAD

**Issue by DiesDasJenes** [getgrav/grav#3124]
Aloha,

Grav is currently on version: v1.6.19
OS is a unix system and up-to-date.

I tried to update grav with the admin panel and got the error: ` Grav update failed rmdir(/var/www/grav/webserver-configs): Directory not empty`. After that i tried to update grav with gpm but i got this error:
```bash
Preparing to upgrade to v1.6.31..
  |- Downloading upgrade [3.94M]...   100%
  |- Installing upgrade...  PHP Fatal error:  Uncaught Error: Class 'ZipArchive' not found in /var/www/grav/system/src/Grav/Common/GPM/Installer.php:175
Stack trace:
#0 /var/www/grav/system/src/Grav/Console/Gpm/SelfupgradeCommand.php(207): Grav\Common\GPM\Installer::unZip()
#1 /var/www/grav/system/src/Grav/Console/Gpm/SelfupgradeCommand.php(165): Grav\Console\Gpm\SelfupgradeCommand->upgrade()
#2 /var/www/grav/system/src/Grav/Console/ConsoleCommand.php(30): Grav\Console\Gpm\SelfupgradeCommand->serve()
#3 /var/www/grav/vendor/symfony/console/Command/Command.php(255): Grav\Console\ConsoleCommand->execute()
#4 /var/www/grav/vendor/symfony/console/Application.php(917): Symfony\Component\Console\Command\Command->run()
#5 /var/www/grav/vendor/symfony/console/Application.php(269): Symfony\Component\Console\Application->doRunCommand()
#6 /var/www/grav/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun()
#7 /var/www/grav/bin/gpm(72): Symfony\Component\Console\Application->run()
#8 {main}
  thrown in /var/www/grav/system/src/Grav/Common/GPM/Installer.php on line 175
```
 
Are more information needed? If yes how can i get the log messages? 
Thanks for help :)

**Comment by rhukster** [comment]
You need to install zip module for php.  That is a requirement for Grav.  How you install that depends on your Linux distro.

**Comment by DiesDasJenes** [comment]
I see then this can be closed.
