### ISSUE TITLE
1.7 Upgrade error

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#3160]
```
$ ./bin/gpm selfupgrade

GPM Releases Configuration: Stable

Grav v1.7.0 is now available [release date: Tue Jan 19 21:13:42 2021].
You are currently using v1.6.31.
Would you like to read the changelog before proceeding? [y|N] 
Would you like to upgrade now? [y|N] y

Preparing to upgrade to v1.7.0..
  |- Downloading upgrade [12.44M]...   100%
  |- Installing upgrade...    ok                             
  '- Success!  

PHP Fatal error:  Uncaught Error: Call to undefined method Grav\Console\Cli\ClearCacheCommand::initializeGrav() in /home/user/grav/system/src/Grav/Console/GravCommand.php:33
Stack trace:
#0 /home/user/grav/vendor/symfony/console/Command/Command.php(255): Grav\Console\GravCommand->execute()
#1 /home/user/grav/system/src/Grav/Console/ConsoleTrait.php(112): Symfony\Component\Console\Command\Command->run()
#2 /home/user/grav/system/src/Grav/Console/Gpm/SelfupgradeCommand.php(186): Grav\Console\ConsoleCommand->clearCache()
#3 /home/user/grav/system/src/Grav/Console/ConsoleCommand.php(41): Grav\Console\Gpm\SelfupgradeCommand->serve()
#4 /home/user/grav/vendor/symfony/console/Command/Command.php(255): Grav\Console\ConsoleCommand->execute()
#5 /home/user/grav/vendor/symfony/console/Application.php(917): Symf in /home/user/grav/system/src/Grav/Console/GravCommand.php on line 33
```

**Comment by mahagr** [comment]
Yeah, it looks like it's not safe to call another CLI command after the underlying files have been replaced.

**Comment by mahagr** [comment]
The upgrade itself did not fail, the command just failed to clear the cache.
