### ISSUE TITLE
Every day : Server Crash

### ISSUE THREAD

**Issue by Ribero** [getgrav/grav#3166]
v1.7.0 - Admin v1.10.0 

Every morning when trying to access the site all users are stuck: Cannot access the grav instance which only displays instead of home page (admin page not accessible too):

`Fatal error: Uncaught RuntimeException: Failed to save file /var/www/html/cache/compiled/blueprints/master-34.91.56.93.php in /var/www/html/vendor/rockettheme/toolbox/File/src/AbstractFile.php:369 Stack trace: #0 /var/www/html/vendor/rockettheme/toolbox/File/src/PhpFile.php(41): RocketTheme\Toolbox\File\AbstractFile->save(Array) #1 /var/www/html/system/src/Grav/Common/Config/CompiledBase.php(255): RocketTheme\Toolbox\File\PhpFile->save(Ar
ray) #2 /var/www/html/system/src/Grav/Common/Config/CompiledBase.php(113): Grav\Common\Config\CompiledBase->saveCompiledFile('/var/www/html/c...') #3 /var/www/html/system/src/Grav/Common/Service/ConfigServiceProvider.php(92): Grav\Common\Config\CompiledBase->load() #4 /var/www/html/system/src/Grav/Common/Service/ConfigServiceProvider.php(45): Grav\Common\Service\ConfigServiceProvider::blueprints(Object(Grav\Common\Grav)) #5 /var/www/html/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\ConfigServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #6 in /var/www/html/vendor/rockettheme/toolbox/File/src/AbstractFile.php on line 369`

Forced to login in the docker container to do a `php ./bin/grav cache --all`

Everyday the Grav server crashes this way making it unusable. 
It is probably linked to a plugin (Presentation, Blue Prints ?) as the log is full of errors regarding blueprints (cf. #3159). I uninstalled all plugins and all themes and reinstalled the Themes after that but no change.  

[logs.zip](https://github.com/getgrav/grav/files/5848063/logs.zip)

**Comment by mahagr** [comment]
Maybe your server changes the file permissions automatically? This error comes when files cannot be saved into the cache folder.

**Comment by Ribero** [comment]
well, the files & folder permissions looks ok except `master-cli.php` :

```
root@253d31ae1e89:/var/www/html/cache/compiled/blueprints# ls -lFa
total 1128
drwxr-xr-x. 2 www-data www-data    102 Jan 21 15:23 ./
drwxr-xr-x. 6 www-data www-data     68 Jan 21 15:15 ../
-rw-r--r--. 1 www-data www-data 398025 Jan 21 15:22 master-xxx.xxx.xxx.xxx.php
**-rw-r--r--. 1 root     root     376519 Jan 21 15:23 master-cli.php**
-rw-r--r--. 1 www-data www-data 376519 Jan 21 15:15 myserver.domain.php
root@253d31ae1e89:/var/www/html/cache/compiled/blueprints# 
```

I changed the right of this owner of the file to reflect the other but just a few hours later I see that the file is once again owned by root. During this time I did not use command line or anything else. Only the Admin Panel Gui.

How to prevent this situation ?

**Comment by mahagr** [comment]
You really don't want to run CLI as root, like.. ever.

You should run it using the same user: `sudo -u www-data bin/grav ...` to keep the file permissions correct on all files.

The permission is correct now, but likely something changes those permissions during the night...?

**Comment by Ribero** [comment]
as stated I do not use any CLI as root... The file owner is changed by another process not by me !

**Comment by rhukster** [comment]
You should also make sure the scheduler command is in your users crontab and not in roots.  If root runs the grav scheduler then the ownership will change to root.  I think this is what you are seeing.

**Comment by Ribero** [comment]
Admin Panel clear cash is done using the scheduler ?

**Comment by rhukster** [comment]
No admin cache clear is done via php running under the web server.  So whatever user runs httpd (or nginx etc)

**Comment by rhukster** [comment]
You mentioned scheduler and I’ve seen the situation here scheduler is running under another users crontab causing permission conflicts.

**Comment by Ribero** [comment]
My test case is not using the scheduler

**Comment by Ribero** [comment]
I can confirm that I have no more issues with clear cache but I lost the ability to schedule backups
