### ISSUE TITLE
PHP Fatal error on bin/gpm plugin uninstall

### ISSUE THREAD

**Issue by travis00001** [getgrav/grav#3207]
with latest stable grav,
```
bin/gpm version gantry5
    You are running Gantry 5 Framework v5.4.37

bin/gpm uninstall gantry5

    Preparing to uninstall Gantry 5 Framework [v5.4.37]
    |- Checking destination...  ok
    `- Dependencies found...

    PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Grav\Console\Gpm\UninstallCommand::packageExists() must be an instance of Grav\Common\GPM\Local\Package, instance of Grav\Common\GPM\Remote\Package given, called in /home/wwwrun/grav01/grav/system/src/Grav/Console/Gpm/UninstallCommand.php on line 205 and defined in /home/wwwrun/grav01/grav/system/src/Grav/Console/Gpm/UninstallCommand.php:303
    Stack trace:
    #0 /home/wwwrun/grav01/grav/system/src/Grav/Console/Gpm/UninstallCommand.php(205): Grav\Console\Gpm\UninstallCommand->packageExists('admin', Object(Grav\Common\GPM\Remote\Package))
    #1 /home/wwwrun/grav01/grav/system/src/Grav/Console/Gpm/UninstallCommand.php(132): Grav\Console\Gpm\UninstallCommand->uninstallPackage('gantry5', Object(Grav\Common\GPM\Local\Package))
    #2 /home/wwwrun/grav01/grav/system/src/Grav/Console/GpmCommand.php(41): Grav\Console\Gpm\UninstallCommand->serve()
    #3 /home/wwwrun/grav01/grav/vendor/symfony/consol in /home/wwwrun/grav01/grav/system/src/Grav/Console/Gpm/UninstallCommand.php on line 303
```

**Comment by rhukster** [comment]
We'll take a look.  In the meantime, the simple work around is to simply delete the plugin folder.
