### ISSUE TITLE
1.7.12 crashes unexpected

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#3318]
I found no real reason why this could happen:
```
$ php -S 0.0.0.0:8000 system/router.php
[Sun Apr 18 08:40:50 2021] PHP 8.0.3 Development Server (http://0.0.0.0:8000) started
[Sun Apr 18 08:40:52 2021] 127.0.0.1:60314 Accepted
[Sun Apr 18 08:40:52 2021] PHP Fatal error:  Uncaught TypeError: Nyholm\Psr7Server\ServerRequestCreator::fromArrays(): Argument #5 ($post) must be of type array, null given, called in /home/user/grav/system/src/Grav/Common/Service/RequestServiceProvider.php on line 96 and defined in /home/user/grav/vendor/kodus/psr7-server/src/ServerRequestCreator.php:60
Stack trace:
#0 /home/user/grav/system/src/Grav/Common/Service/RequestServiceProvider.php(96): Nyholm\Psr7Server\ServerRequestCreator->fromArrays()
#1 /home/user/grav/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\RequestServiceProvider->Grav\Common\Service\{closure}()
#2 /home/user/grav/system/src/Grav/Common/Config/Setup.php(185): Pimple\Container->offsetGet()
#3 /home/user/grav/system/src/Grav/Common/Service/ConfigServiceProvider.php(38): Grav\Common\Config\Setup->__construct()
#4 /home/user/grav/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\ConfigServiceProvider->Grav\Common\Service\{closure}()
#5 /home/user/grav/system/src/Grav/Common/Grav.php(203): Pimple\Container->offsetGet()
#6 /home/user/grav/system/src/Grav/Common/Grav.php(244): Grav\Common\Grav->setup()
#7 /home/user/grav/index.php(58): Grav\Common\Grav->process()
#8 {main}
  thrown in /home/user/grav/vendor/kodus/psr7-server/src/ServerRequestCreator.php on line 60
[Sun Apr 18 08:40:52 2021] 127.0.0.1:60314 [500]: GET / - Uncaught TypeError: Nyholm\Psr7Server\ServerRequestCreator::fromArrays(): Argument #5 ($post) must be of type array, null given, called in /home/user/grav/system/src/Grav/Common/Service/RequestServiceProvider.php on line 96 and defined in /home/user/grav/vendor/kodus/psr7-server/src/ServerRequestCreator.php:60
Stack trace:
#0 /home/user/grav/system/src/Grav/Common/Service/RequestServiceProvider.php(96): Nyholm\Psr7Server\ServerRequestCreator->fromArrays()
#1 /home/user/grav/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\RequestServiceProvider->Grav\Common\Service\{closure}()
#2 /home/user/grav/system/src/Grav/Common/Config/Setup.php(185): Pimple\Container->offsetGet()
#3 /home/user/grav/system/src/Grav/Common/Service/ConfigServiceProvider.php(38): Grav\Common\Config\Setup->__construct()
#4 /home/user/grav/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\ConfigServiceProvider->Grav\Common\Service\{closure}()
#5 /home/user/grav/system/src/Grav/Common/Grav.php(203): Pimple\Container->offsetGet()
#6 /home/user/grav/system/src/Grav/Common/Grav.php(244): Grav\Common\Grav->setup()
#7 /home/user/grav/index.php(58): Grav\Common\Grav->process()
#8 {main}
  thrown in /home/user/grav/vendor/kodus/psr7-server/src/ServerRequestCreator.php on line 60
[Sun Apr 18 08:40:52 2021] 127.0.0.1:60314 Closing
```

**Comment by mahagr** [comment]
You're using some super old version of `nyholm/psr7-server` library. If you're using git version of Grav, you need to keep composer dependencies up to date by running `composer install` now and then.

**Comment by NicoHood** [comment]
Cool! thank you! :-)
