### ISSUE TITLE
Errors with "bin/gpm update" and "bin/gpm index"

### ISSUE THREAD

**Issue by Mehditerranee** [getgrav/grav#3443]
Hi,

I have just upgraded my Grav website from 1.6 to 1.7 with this command: `bin/gpm selfupgrade`
I followed as possible the instructions [here](https://learn.getgrav.org/17/advanced/grav-development/grav-17-upgrade-guide)

But when I run the command `bin/gpm update` i get these errors:

```
PHP Fatal error:  Uncaught TypeError: RocketTheme\Toolbox\Blueprints\BlueprintSchema::mergeArrays(): Argument #3 ($rules) must be of type array, string given, called in /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/vendor/rockettheme/toolbox/Blueprints/src/BlueprintSchema.php on line 447 and defined in /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/vendor/rockettheme/toolbox/Blueprints/src/BlueprintSchema.php:438
Stack trace:
#0 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/vendor/rockettheme/toolbox/Blueprints/src/BlueprintSchema.php(447): RocketTheme\Toolbox\Blueprints\BlueprintSchema->mergeArrays(Array, Array, '')
#1 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/vendor/rockettheme/toolbox/Blueprints/src/BlueprintSchema.php(247): RocketTheme\Toolbox\Blueprints\BlueprintSchema->mergeArrays(Array, Array, Array)
#2 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/system/src/Grav/Common/Data/Blueprint.php(231): RocketTheme\Toolbox\Blueprints\BlueprintSchema->mergeData(Array, Array, NULL, '.')
#3 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/system/src/Grav/Common/Data/Data.php(205): Grav\Common\Data\Blueprint->mergeData(Array, Array)
#4 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/system/src/Grav/Common/Themes.php(197): Grav\Common\Data\Data->merge(Array)
#5 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/system/src/Grav/Common/Themes.php(141): Grav\Common\Themes->get('mytheme')
#6 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/system/src/Grav/Common/GPM/Local/Themes.php(31): Grav\Common\Themes->all()
#7 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/system/src/Grav/Common/GPM/Local/Packages.php(24): Grav\Common\GPM\Local\Themes->__construct()
#8 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/system/src/Grav/Common/GPM/GPM.php(66): Grav\Common\GPM\Local\Packages->__construct()
#9 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/system/src/Grav/Console/Gpm/UpdateCommand.php(131): Grav\Common\GPM\GPM->__construct(false)
#10 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/system/src/Grav/Console/GpmCommand.php(41): Grav\Console\Gpm\UpdateCommand->serve()
#11 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/vendor/symfony/console/Command/Command.php(255): Grav\Console\GpmCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Grav\Console\Gpm\UpdateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/bin/gpm(54): Symfony\Component\Console\Application->run()
#16 {main}
  thrown in /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/vendor/rockettheme/toolbox/Blueprints/src/BlueprintSchema.php on line 438

Fatal error: Uncaught TypeError: RocketTheme\Toolbox\Blueprints\BlueprintSchema::mergeArrays(): Argument #3 ($rules) must be of type array, string given, called in /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/vendor/rockettheme/toolbox/Blueprints/src/BlueprintSchema.php on line 447 and defined in /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/vendor/rockettheme/toolbox/Blueprints/src/BlueprintSchema.php:438
Stack trace:
#0 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/vendor/rockettheme/toolbox/Blueprints/src/BlueprintSchema.php(447): RocketTheme\Toolbox\Blueprints\BlueprintSchema->mergeArrays(Array, Array, '')
#1 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/vendor/rockettheme/toolbox/Blueprints/src/BlueprintSchema.php(247): RocketTheme\Toolbox\Blueprints\BlueprintSchema->mergeArrays(Array, Array, Array)
#2 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/system/src/Grav/Common/Data/Blueprint.php(231): RocketTheme\Toolbox\Blueprints\BlueprintSchema->mergeData(Array, Array, NULL, '.')
#3 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/system/src/Grav/Common/Data/Data.php(205): Grav\Common\Data\Blueprint->mergeData(Array, Array)
#4 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/system/src/Grav/Common/Themes.php(197): Grav\Common\Data\Data->merge(Array)
#5 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/system/src/Grav/Common/Themes.php(141): Grav\Common\Themes->get('mytheme')
#6 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/system/src/Grav/Common/GPM/Local/Themes.php(31): Grav\Common\Themes->all()
#7 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/system/src/Grav/Common/GPM/Local/Packages.php(24): Grav\Common\GPM\Local\Themes->__construct()
#8 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/system/src/Grav/Common/GPM/GPM.php(66): Grav\Common\GPM\Local\Packages->__construct()
#9 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/system/src/Grav/Console/Gpm/UpdateCommand.php(131): Grav\Common\GPM\GPM->__construct(false)
#10 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/system/src/Grav/Console/GpmCommand.php(41): Grav\Console\Gpm\UpdateCommand->serve()
#11 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/vendor/symfony/console/Command/Command.php(255): Grav\Console\GpmCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Grav\Console\Gpm\UpdateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/bin/gpm(54): Symfony\Component\Console\Application->run()
#16 {main}
  thrown in /Users/gamecube/Documents/MAMP Websites/mehdigallois.fr/vendor/rockettheme/toolbox/Blueprints/src/BlueprintSchema.php on line 438
```

I suspect an issue in the theme tree view.
Here my theme folder:
[mytheme.zip](https://github.com/getgrav/grav/files/7190089/mytheme.zip)

Any idea ?

**Comment by rhukster** [comment]
Have you looked at this yet? https://learn.getgrav.org/16/advanced/grav-development/grav-17-upgrade-guide

**Comment by Mehditerranee** [comment]
@rhukster  yes I try to follow the part about Blueprint because it seems to be related on this.

The explanations are not really clear : it is advise to move Blueprint folder content to Blueprint/pages/
However, there is no Blueprint folder in my theme (cf. mytheme.zip above), so I don't understand.

**Comment by rhukster** [comment]
Just create the blueprints folder.

**Comment by Mehditerranee** [comment]
@rhukster I created it with `pages` sub-folder.

However, I think I should also create .yaml files for each modular parts of my theme.
But I don't know how to create them (content), and this, even if I check and compare with an already compatible theme like this one (Antimatter): https://github.com/getgrav/grav-theme-antimatter/tree/develop/blueprints

Is there a documention/tutorial about how create yaml blueprints files?

**Comment by rhukster** [comment]
https://learn.getgrav.org/17/forms/blueprints

**Comment by mahagr** [comment]
You have a configuration file that replaces an array with an empty string. Basically, there's an illegal value in some of your yaml files.

**Comment by mahagr** [comment]
I just pushed commit to the rockettheme/toolbox to fix this error: https://github.com/rockettheme/toolbox/commit/550f496bf28f81ffc1c228abb72d9af3dcbff072

**Comment by Mehditerranee** [comment]
@mahagr Thank you for your reply. 

Yet, I used the command : `bin/grav yamllinter` and i fixed all errors. 
Despite that, i get the same error with `bin/gpm update` and `bin/gpm index`.

It could be useful to detect an illegal value in a yaml file with this command. (`bin/grav yamllinter`)

I going to retry with your fix.

**Comment by Mehditerranee** [comment]
**✓ I solved my issue ✓** 

The issue came from the yaml of the theme `mytheme.yaml` where the indentation was not correct.

Former content (without indentation):
```
streams:
schemes:
theme:
type: ReadOnlyStream
prefixes:
paths:
- user/themes/mytheme
- user/themes/woo
```

New content (edited with indentation):
```
streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
      paths:
      - user/themes/mytheme
      - user/themes/woo
```

Now `bin/gpm update` and `bin/gpm index` works

**Comment by mahagr** [comment]
I already did a fix on this, though in your case, it'll likely just break the site in another way.

There's really no way to detect badly copied files from the good configuration.
