### ISSUE TITLE
Grav running but can't run the bin scripts

### ISSUE THREAD

**Issue by domsson** [getgrav/grav#3460]
Not sure if this is an issue with the server I just set up (probably), but I'm stuck and decided to report it anyway; just in case:
 
 Base/demo page running fine, but when calling bin/grav or bin/gpm, for example `bin/gpm install devtools`, I get this error:
 
```
  Preparing to install DevTools [v1.5.3]
  |- Downloading package...     0%PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\Component\HttpClient\HttpOptions::setOnProgress() must be callable, array given, called in /var/www/redacted/system/src/Grav/Common/HTTP/Client.php on line 36 and defined in /var/www/redacted/vendor/symfony/http-client/HttpOptions.php:153
Stack trace:
#0 /var/www/redacted/system/src/Grav/Common/HTTP/Client.php(36): Symfony\Component\HttpClient\HttpOptions->setOnProgress()
#1 /var/www/redacted/system/src/Grav/Common/HTTP/Response.php(78): Grav\Common\HTTP\Client::getClient()
#2 /var/www/redacted/system/src/Grav/Common/HTTP/Response.php(46): Grav\Common\HTTP\Response::request()
#3 /var/www/redacted/system/src/Grav/Console/Gpm/InstallCommand.php(601): Grav\Common\HTTP\Response::get()
#4 /var/www/redacted/system/src/Grav/Console/Gpm/InstallCommand.php(539): Grav\Console\Gpm\InstallCommand->downloadPackage()
#5 /var/www/redacted/system/src/Grav/Console/Gpm/InstallCommand.php(357): Grav\Console\Gpm\InstallCommand->processGpm()
#6 /var/www/redacted/system/src/Grav/Console/Gpm/ in /var/www/redacted/vendor/symfony/http-client/HttpOptions.php on line 153
```

**Comment by mahagr** [comment]
I believe this has already been fixed by this commit: https://github.com/getgrav/grav/commit/11decd588950d1d2238ee4d4429007a111b0b60b

**Comment by wakqasahmed** [comment]
Looks already fixed on `develop` -- `Client::getClient()` now passes `Client::progress(...)` (a first-class callable) to `HttpOptions::setOnProgress()` instead of the old array-style callable that didn't satisfy Symfony's `callable` type hint. Might be worth closing unless it's still reproducible on a current build.
