### ISSUE TITLE
Page edit iconv() issue after upgrade to Grav v1.7.41 - Admin v1.10.41.1

### ISSUE THREAD

**Issue by trianity** [getgrav/grav#3717]
This is a production site, and the front of the website is working without issue after upgrading.

The admin panel accessible, but any page edit link did not work.

System: Grav v1.7.41
Admin v1.10.41.1
PHP 8.1.17

The cache was deleted refreshed, double checked the issue.

The issue is related to "symfony/polyfill-iconv"

Error log: 
```
[2023-05-10 15:35:39] grav.CRITICAL: An exception has been thrown during the rendering of a template ("iconv(): Detected an illegal character in input string"). - Trace:
#0 /path-to-grav/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling()
#1 /path-to-grav/cache/twig/a8/a8a343a534006ba32b0739b9bcfa18b4c1754e800ad73e459613c4f2b6c13fb1.php(116): Twig\Template->display()
#2 /path-to-grav/vendor/twig/twig/src/Template.php(214): __TwigTemplate_da2e25503bd551e89ca2e4b3bc885536dfa8841c6bff41dd872271f5f2f868ce->block_field()
#3 /path-to-grav/cache/twig/a8/a8a343a534006ba32b0739b9bcfa18b4c1754e800ad73e459613c4f2b6c13fb1.php(73): Twig\Template->displayBlock()
#4 /path-to-grav/vendor/twig/twig/src/Template.php(453): __TwigTemplate_da2e25503bd551e89ca2e4b3bc885536dfa8841c6bff41dd872271f5f2f868ce->doDisplay()
#5 /path-to-grav/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling()
#6 /path-to-grav/cache/twig/48/488373266cca77ba3e53b70498608d517f4c21a267bd32eb266f48d4b25d3f68.php(104): Twig\Template->display()
#7 /path-to-grav/vendor/twig/twig/src/Template.php(453): __TwigTemplate_db03dc87c8c3926fb29e80e0f6d93ddb6adceb13e0e4401af73d216ea1c53a2d___335022848->doDisplay()
#8 /path-to-grav/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling()
#9 /path-to-grav/cache/twig/48/488373266cca77ba3e53b70498608d517f4c21a267bd32eb266f48d4b25d3f68.php(43): Twig\Template->display()
#10 /path-to-grav/vendor/twig/twig/src/Template.php(214): __TwigTemplate_db03dc87c8c3926fb29e80e0f6d93ddb6adceb13e0e4401af73d216ea1c53a2d->block_field()
#11 /path-to-grav/cache/twig/87/872d8ba22fa04cbfd220ca12f3015fb5065ee4a9e3aa60877b723cb17aa9befa.php(108): Twig\Template->displayBlock()
#12 /path-to-grav/vendor/twig/twig/src/Template.php(453): __TwigTemplate_ad54a098d3a72a477f29d282fed40f6cf8c8471f03c2d0de4ab21b4dfb497974->doDisplay()
#13 /path-to-grav/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling()
#14 /path-to-grav/cache/twig/48/488373266cca77ba3e53b70498608d517f4c21a267bd32eb266f48d4b25d3f68.php(35): Twig\Template->display()
#15 /path-to-grav/vendor/twig/twig/src/Template.php(453): __TwigTemplate_db03dc87c8c3926fb29e80e0f6d93ddb6adceb13e0e4401af73d216ea1c53a2d->doDisplay()
#16 /path-to-grav/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling()
#17 /path-to-grav/cache/twig/a8/a8a343a534006ba32b0739b9bcfa18b4c1754e800ad73e459613c4f2b6c13fb1.php(116): Twig\Template->display()
#18 /path-to-grav/vendor/twig/twig/src/Template.php(214): __TwigTemplate_da2e25503bd551e89ca2e4b3bc885536dfa8841c6bff41dd872271f5f2f868ce->block_field()
#19 /path-to-grav/cache/twig/a8/a8a343a534006ba32b0739b9bcfa18b4c1754e800ad73e459613c4f2b6c13fb1.php(73): Twig\Template->displayBlock()
#20 /path-to-grav/vendor/twig/twig/src/Template.php(453): __TwigTemplate_da2e25503bd551e89ca2e4b3bc885536dfa8841c6bff41dd872271f5f2f868ce->doDisplay()
#21 /path-to-grav/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling()
#22 /path-to-grav/cache/twig/fe/fe7e203163b567f69e75eb1faeb3f3a63e4b59f9907a882456d57b3f293c20bf.php(346): Twig\Template->display()
#23 /path-to-grav/vendor/twig/twig/src/Template.php(453): __TwigTemplate_2e7f0760a6fea681ebf59ab521483a4b6fe06a5ea0c38e3dc2d707f3ef4d68a7___960203896->doDisplay()
#24 /path-to-grav/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling()
#25 /path-to-grav/cache/twig/fe/fe7e203163b567f69e75eb1faeb3f3a63e4b59f9907a882456d57b3f293c20bf.php(223): Twig\Template->display()
#26 /path-to-grav/vendor/twig/twig/src/Template.php(214): __TwigTemplate_2e7f0760a6fea681ebf59ab521483a4b6fe06a5ea0c38e3dc2d707f3ef4d68a7->block_field()
#27 /path-to-grav/cache/twig/87/872d8ba22fa04cbfd220ca12f3015fb5065ee4a9e3aa60877b723cb17aa9befa.php(108): Twig\Template->displayBlock()
#28 /path-to-grav/vendor/twig/twig/src/Template.php(453): __TwigTemplate_ad54a098d3a72a477f29d282fed40f6cf8c8471f03c2d0de4ab21b4dfb497974->doDisplay()
#29 /path-to-grav/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling()
#30 /path-to-grav/cache/twig/fe/fe7e203163b567f69e75eb1faeb3f3a63e4b59f9907a882456d57b3f293c20bf.php(43): Twig\Template->display()
#31 /path-to-grav/vendor/twig/twig/src/Template.php(453): __TwigTemplate_2e7f0760a6fea681ebf59ab521483a4b6fe06a5ea0c38e3dc2d707f3ef4d68a7->doDisplay()
#32 /path-to-grav/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling()
#33 /path-to-grav/cache/twig/a8/a8a343a534006ba32b0739b9bcfa18b4c1754e800ad73e459613c4f2b6c13fb1.php(116): Twig\Template->display()
#34 /path-to-grav/vendor/twig/twig/src/Template.php(214): __TwigTemplate_da2e25503bd551e89ca2e4b3bc885536dfa8841c6bff41dd872271f5f2f868ce->block_field()
#35 /path-to-grav/cache/twig/a8/a8a343a534006ba32b0739b9bcfa18b4c1754e800ad73e459613c4f2b6c13fb1.php(73): Twig\Template->displayBlock()
#36 /path-to-grav/vendor/twig/twig/src/Template.php(453): __TwigTemplate_da2e25503bd551e89ca2e4b3bc885536dfa8841c6bff41dd872271f5f2f868ce->doDisplay()
#37 /path-to-grav/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling()
#38 /path-to-grav/cache/twig/48/488373266cca77ba3e53b70498608d517f4c21a267bd32eb266f48d4b25d3f68.php(104): Twig\Template->display()
#39 /path-to-grav/vendor/twig/twig/src/Template.php(453): __TwigTemplate_db03dc87c8c3926fb29e80e0f6d93ddb6adceb13e0e4401af73d216ea1c53a2d___335022848->doDisplay()
#40 /path-to-grav/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling()
#41 /path-to-grav/cache/twig/48/488373266cca77ba3e53b70498608d517f4c21a267bd32eb266f48d4b25d3f68.php(43): Twig\Template->display()
#42 /path-to-grav/vendor/twig/twig/src/Template.php(214): __TwigTemplate_db03dc87c8c3926fb29e80e0f6d93ddb6adceb13e0e4401af73d216ea1c53a2d->block_field()
#43 /path-to-grav/cache/twig/87/872d8ba22fa04cbfd220ca12f3015fb5065ee4a9e3aa60877b723cb17aa9befa.php(108): Twig\Template->displayBlock()
#44 /path-to-grav/vendor/twig/twig/src/Template.php(453): __TwigTemplate_ad54a098d3a72a477f29d282fed40f6cf8c8471f03c2d0de4ab21b4dfb497974->doDisplay()
#45 /path-to-grav/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling()
#46 /path-to-grav/cache/twig/48/488373266cca77ba3e53b70498608d517f4c21a267bd32eb266f48d4b25d3f68.php(35): Twig\Template->display()
#47 /path-to-grav/vendor/twig/twig/src/Template.php(453): __TwigTemplate_db03dc87c8c3926fb29e80e0f6d93ddb6adceb13e0e4401af73d216ea1c53a2d->doDisplay()
#48 /path-to-grav/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling()
#49 /path-to-grav/cache/twig/a8/a8a343a534006ba32b0739b9bcfa18b4c1754e800ad73e459613c4f2b6c13fb1.php(116): Twig\Template->display()
#50 /path-to-grav/vendor/twig/twig/src/Template.php(214): __TwigTemplate_da2e25503bd551e89ca2e4b3bc885536dfa8841c6bff41dd872271f5f2f868ce->block_field()
#51 /path-to-grav/cache/twig/a8/a8a343a534006ba32b0739b9bcfa18b4c1754e800ad73e459613c4f2b6c13fb1.php(73): Twig\Template->displayBlock()
#52 /path-to-grav/vendor/twig/twig/src/Template.php(453): __TwigTemplate_da2e25503bd551e89ca2e4b3bc885536dfa8841c6bff41dd872271f5f2f868ce->doDisplay()
#53 /path-to-grav/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling()
#54 /path-to-grav/cache/twig/fe/fe7e203163b567f69e75eb1faeb3f3a63e4b59f9907a882456d57b3f293c20bf.php(346): Twig\Template->display()
#55 /path-to-grav/vendor/twig/twig/src/Template.php(453): __TwigTemplate_2e7f0760a6fea681ebf59ab521483a4b6fe06a5ea0c38e3dc2d707f3ef4d68a7___960203896->doDisplay()
#56 /path-to-grav/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling()
#57 /path-to-grav/cache/twig/fe/fe7e203163b567f69e75eb1faeb3f3a63e4b59f9907a882456d57b3f293c20bf.php(223): Twig\Template->display()
#58 /path-to-grav/vendor/twig/twig/src/Template.php(214): __TwigTemplate_2e7f0760a6fea681ebf59ab521483a4b6fe06a5ea0c38e3dc2d707f3ef4d68a7->block_field()
#59 /path-to-grav/cache/twig/87/872d8ba22fa04cbfd220ca12f3015fb5065ee4a9e3aa60877b723cb17aa9befa.php(108): Twig\Template->displayBlock()
#60 /path-to-grav/vendor/twig/twig/src/Template.php(453): __TwigTemplate_ad54a098d3a72a477f29d282fed40f6cf8c8471f03c2d0de4ab21b4dfb497974->doDisplay()
#61 /path-to-grav/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling()
#62 /path-to-grav/cache/twig/fe/fe7e203163b567f69e75eb1faeb3f3a63e4b59f9907a882456d57b3f293c20bf.php(43): Twig\Template->display()
#63 /path-to-grav/vendor/twig/twig/src/Template.php(453): __TwigTemplate_2e7f0760a6fea681ebf59ab521483a4b6fe06a5ea0c38e3dc2d707f3ef4d68a7->doDisplay()
#64 /path-to-grav/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling()
#65 /path-to-grav/cache/twig/a8/a8a343a534006ba32b0739b9bcfa18b4c1754e800ad73e459613c4f2b6c13fb1.php(116): Twig\Template->display()
#66 /path-to-grav/vendor/twig/twig/src/Template.php(214): __TwigTemplate_da2e25503bd551e89ca2e4b3bc885536dfa8841c6bff41dd872271f5f2f868ce->block_field()
#67 /path-to-grav/cache/twig/a8/a8a343a534006ba32b0739b9bcfa18b4c1754e800ad73e459613c4f2b6c13fb1.php(73): Twig\Template->displayBlock()
#68 /path-to-grav/vendor/twig/twig/src/Template.php(453): __TwigTemplate_da2e25503bd551e89ca2e4b3bc885536dfa8841c6bff41dd872271f5f2f868ce->doDisplay()
#69 /path-to-grav/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling()
#70 /path-to-grav/cache/twig/ca/cadd39602714ae2401308000f53d9743bc06d7a37f1803f6332678a5a84eb8b4.php(240): Twig\Template->display()
#71 /path-to-grav/vendor/twig/twig/src/Template.php(453): __TwigTemplate_537f7b9f3035d493451a33f81438b4baf1dde7d6339f8314c79be63c5d54451c___1933465276->doDisplay()
#72 /path-to-grav/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling()
#73 /path-to-grav/cache/twig/ca/cadd39602714ae2401308000f53d9743bc06d7a37f1803f6332678a5a84eb8b4.php(70): Twig\Template->display()
#74 /path-to-grav/vendor/twig/twig/src/Template.php(453): __TwigTemplate_537f7b9f3035d493451a33f81438b4baf1dde7d6339f8314c79be63c5d54451c->doDisplay()
#75 /path-to-grav/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling()
#76 /path-to-grav/cache/twig/cb/cb8ccec994bcf08f19ccbbbd3a5a506cefdd46880ecb83619b2bf4bf504ae7a8.php(492): Twig\Template->display()
#77 /path-to-grav/vendor/twig/twig/src/Template.php(214): __TwigTemplate_bb7140a0cc8f2bf0bdfb8bda0ba5f51d343e844003e769b1a1239f3dcfd53cae->block_edit()
#78 /path-to-grav/cache/twig/5d/5d7d9e7f30e6869e08d449008e180dd493a0d1c1f189501535152864e7285376.php(199): Twig\Template->displayBlock()
#79 /path-to-grav/vendor/twig/twig/src/Template.php(214): __TwigTemplate_03deba2c2408dbccc269430c1ea71e7d306e546f62b997948f8bd99c64106ecf->block_content()
#80 /path-to-grav/vendor/twig/twig/src/Template.php(175): Twig\Template->displayBlock()
#81 /path-to-grav/cache/twig/cb/cb8ccec994bcf08f19ccbbbd3a5a506cefdd46880ecb83619b2bf4bf504ae7a8.php(500): Twig\Template->displayParentBlock()
#82 /path-to-grav/vendor/twig/twig/src/Template.php(214): __TwigTemplate_bb7140a0cc8f2bf0bdfb8bda0ba5f51d343e844003e769b1a1239f3dcfd53cae->block_content()
#83 /path-to-grav/cache/twig/62/62188ad725e44b7f0b039b5cdde43db572f56d62b0d92cb5f8e5007bdce95623.php(318): Twig\Template->displayBlock()
#84 /path-to-grav/vendor/twig/twig/src/Template.php(214): __TwigTemplate_3800ec1529f3814ebfca3ed3fdff117aa9fa852ac30f5ec248a209604ea68768->block_content_wrapper()
#85 /path-to-grav/cache/twig/62/62188ad725e44b7f0b039b5cdde43db572f56d62b0d92cb5f8e5007bdce95623.php(262): Twig\Template->displayBlock()
#86 /path-to-grav/vendor/twig/twig/src/Template.php(214): __TwigTemplate_3800ec1529f3814ebfca3ed3fdff117aa9fa852ac30f5ec248a209604ea68768->block_page()
#87 /path-to-grav/cache/twig/62/62188ad725e44b7f0b039b5cdde43db572f56d62b0d92cb5f8e5007bdce95623.php(222): Twig\Template->displayBlock()
#88 /path-to-grav/vendor/twig/twig/src/Template.php(214): __TwigTemplate_3800ec1529f3814ebfca3ed3fdff117aa9fa852ac30f5ec248a209604ea68768->block_body()
#89 /path-to-grav/vendor/twig/twig/src/Template.php(234): Twig\Template->displayBlock()
#90 /path-to-grav/vendor/twig/twig/src/Template.php(175): Twig\Template->displayBlock()
#91 /path-to-grav/cache/twig/5d/5d7d9e7f30e6869e08d449008e180dd493a0d1c1f189501535152864e7285376.php(134): Twig\Template->displayParentBlock()
#92 /path-to-grav/vendor/twig/twig/src/Template.php(214): __TwigTemplate_03deba2c2408dbccc269430c1ea71e7d306e546f62b997948f8bd99c64106ecf->block_body()
#93 /path-to-grav/vendor/twig/twig/src/Template.php(175): Twig\Template->displayBlock()
#94 /path-to-grav/cache/twig/cb/cb8ccec994bcf08f19ccbbbd3a5a506cefdd46880ecb83619b2bf4bf504ae7a8.php(120): Twig\Template->displayParentBlock()
#95 /path-to-grav/vendor/twig/twig/src/Template.php(214): __TwigTemplate_bb7140a0cc8f2bf0bdfb8bda0ba5f51d343e844003e769b1a1239f3dcfd53cae->block_body()
#96 /path-to-grav/cache/twig/62/62188ad725e44b7f0b039b5cdde43db572f56d62b0d92cb5f8e5007bdce95623.php(76): Twig\Template->displayBlock()
#97 /path-to-grav/vendor/twig/twig/src/Template.php(453): __TwigTemplate_3800ec1529f3814ebfca3ed3fdff117aa9fa852ac30f5ec248a209604ea68768->doDisplay()
#98 /path-to-grav/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling()
#99 /path-to-grav/cache/twig/f3/f3a7484da6b42f51476aa3ff0253d7bc580fa5f1240547a96df8f800cd674de1.php(34): Twig\Template->display()
#100 /path-to-grav/vendor/twig/twig/src/Template.php(453): __TwigTemplate_4956a22d2c67ddafcc9c5097a27a270e90daeae0f7c3ce5b22b438925067d1c5->doDisplay()
#101 /path-to-grav/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling()
#102 /path-to-grav/cache/twig/5d/5d7d9e7f30e6869e08d449008e180dd493a0d1c1f189501535152864e7285376.php(115): Twig\Template->display()
#103 /path-to-grav/vendor/twig/twig/src/Template.php(453): __TwigTemplate_03deba2c2408dbccc269430c1ea71e7d306e546f62b997948f8bd99c64106ecf->doDisplay()
#104 /path-to-grav/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling()
#105 /path-to-grav/cache/twig/cb/cb8ccec994bcf08f19ccbbbd3a5a506cefdd46880ecb83619b2bf4bf504ae7a8.php(73): Twig\Template->display()
#106 /path-to-grav/vendor/twig/twig/src/Template.php(453): __TwigTemplate_bb7140a0cc8f2bf0bdfb8bda0ba5f51d343e844003e769b1a1239f3dcfd53cae->doDisplay()
#107 /path-to-grav/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling()
#108 /path-to-grav/cache/twig/a2/a2179c9aeff4ef1ebd86893850723c1c23ac3bc14928e92da92eed73e2606376.php(64): Twig\Template->display()
#109 /path-to-grav/vendor/twig/twig/src/Template.php(453): __TwigTemplate_3b4e8473733b45731b5a6233e808dd0e54c64f465ba151c1ba6b6374710b526c->doDisplay()
#110 /path-to-grav/vendor/twig/twig/src/Template.php(420): Twig\Template->displayWithErrorHandling()
#111 /path-to-grav/vendor/twig/twig/src/Template.php(432): Twig\Template->display()
#112 /path-to-grav/vendor/twig/twig/src/TemplateWrapper.php(47): Twig\Template->render()
#113 /path-to-grav/vendor/twig/twig/src/Environment.php(384): Twig\TemplateWrapper->render()
#114 /path-to-grav/system/src/Grav/Common/Twig/Twig.php(448): Twig\Environment->render()
#115 /path-to-grav/system/src/Grav/Common/Service/OutputServiceProvider.php(36): Grav\Common\Twig\Twig->processSite()
#116 /path-to-grav/vendor/pimple/pimple/src/Pimple/Container.php(122): Grav\Common\Service\OutputServiceProvider->Grav\Common\Service\{closure}()
#117 /path-to-grav/system/src/Grav/Common/Processors/RenderProcessor.php(40): Pimple\Container->offsetGet()
#118 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\RenderProcessor->process()
#119 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle()
#120 /path-to-grav/system/src/Grav/Common/Processors/DebuggerAssetsProcessor.php(38): Grav\Framework\RequestHandler\RequestHandler->handle()
#121 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\DebuggerAssetsProcessor->process()
#122 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle()
#123 /path-to-grav/system/src/Grav/Common/Processors/PagesProcessor.php(113): Grav\Framework\RequestHandler\RequestHandler->handle()
#124 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\PagesProcessor->process()
#125 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle()
#126 /path-to-grav/system/src/Grav/Common/Processors/TwigProcessor.php(38): Grav\Framework\RequestHandler\RequestHandler->handle()
#127 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\TwigProcessor->process()
#128 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle()
#129 /path-to-grav/system/src/Grav/Common/Processors/AssetsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle()
#130 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\AssetsProcessor->process()
#131 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle()
#132 /path-to-grav/system/src/Grav/Common/Processors/SchedulerProcessor.php(40): Grav\Framework\RequestHandler\RequestHandler->handle()
#133 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\SchedulerProcessor->process()
#134 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle()
#135 /path-to-grav/system/src/Grav/Common/Processors/BackupsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle()
#136 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\BackupsProcessor->process()
#137 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle()
#138 /path-to-grav/system/src/Grav/Common/Processors/TasksProcessor.php(69): Grav\Framework\RequestHandler\RequestHandler->handle()
#139 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\TasksProcessor->process()
#140 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle()
#141 /path-to-grav/user/plugins/admin/classes/plugin/Router.php(72): Grav\Framework\RequestHandler\RequestHandler->handle()
#142 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Plugin\Admin\Router->process()
#143 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle()
#144 /path-to-grav/system/src/Grav/Common/Processors/RequestProcessor.php(64): Grav\Framework\RequestHandler\RequestHandler->handle()
#145 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\RequestProcessor->process()
#146 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle()
#147 /path-to-grav/system/src/Grav/Common/Processors/ThemesProcessor.php(38): Grav\Framework\RequestHandler\RequestHandler->handle()
#148 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\ThemesProcessor->process()
#149 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle()
#150 /path-to-grav/system/src/Grav/Common/Processors/PluginsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle()
#151 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\PluginsProcessor->process()
#152 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle()
#153 /path-to-grav/system/src/Grav/Common/Processors/InitializeProcessor.php(130): Grav\Framework\RequestHandler\RequestHandler->handle()
#154 /path-to-grav/system/src/Grav/Common/Debugger.php(546): Grav\Common\Processors\InitializeProcessor::Grav\Common\Processors\{closure}()
#155 /path-to-grav/system/src/Grav/Common/Processors/InitializeProcessor.php(131): Grav\Common\Debugger->profile()
#156 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\InitializeProcessor->process()
#157 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle()
#158 /path-to-grav/system/src/Grav/Framework/RequestHandler/Middlewares/MultipartRequestSupport.php(40): Grav\Framework\RequestHandler\RequestHandler->handle()
#159 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Framework\RequestHandler\Middlewares\MultipartRequestSupport->process()
#160 /path-to-grav/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle()
#161 /path-to-grav/system/src/Grav/Common/Grav.php(312): Grav\Framework\RequestHandler\RequestHandler->handle()
#162 /path-to-grav/index.php(47): Grav\Common\Grav->process()
#163 {main} [] []
```

**Comment by rhukster** [comment]
Force a "check updates" and install Grav `1.7.41.1` which has a fix for this

**Comment by trianity** [comment]
Thank you, the suggested solutions works, the issue was fixed.
