### ISSUE TITLE
Grav isn't parsing url parameters (throws an error)

### ISSUE THREAD

**Issue by signorekai** [getgrav/grav#528]
I'm running Grav on Nginx installed on Ubuntu 14.04, and for some reason it's not parsing url parameters. When I go to ``` grav/admin/pages/home/_showcase/mode:normal ```, for example, it pushes out a page's worth of errors. I've tried searching around but couldn't find anything. Would appreciate any help!

grav.log reads the following:

```
[2015-12-14 13:24:04] grav.CRITICAL: mkdir(): Invalid path - Trace: #0 [internal function]: Whoops\Run->handleError(2, 'mkdir(): Invali...', '/path/to/grav/...', 30, Array) #1 /path/to/grav/system/src/Grav/Common/Twig/WriteCacheFileTrait.php(30): mkdir('', 511, true) #2 /path/to/grav/vendor/twig/twig/lib/Twig/Environment.php(398): Grav\Common\Twig\TwigEnvironment->writeCacheFile('', '<?php??/* pages...') #3 /path/to/grav/vendor/twig/twig/lib/Twig/Environment.php(347): Twig_Environment->loadTemplate('pages.html.twig') #4 /path/to/grav/system/src/Grav/Common/Twig/Twig.php(322): Twig_Environment->render('pages.html.twig', Array) #5 /path/to/grav/system/src/Grav/Common/Grav.php(157): Grav\Common\Twig\Twig->processSite(NULL) #6 /path/to/grav/vendor/pimple/pimple/src/Pimple/Container.php(113): Grav\Common\Grav::Grav\Common\{closure}(Object(Grav\Common\Grav)) #7 /path/to/grav/system/src/Grav/Common/Grav.php(257): Pimple\Container->offsetGet('output') #8 /path/to/grav/index.php(37): Grav\Common\Grav->process() #9 {main} [] []
```

**Comment by flaviocopes** [comment]
`path/to/grav` is a fake path you added to the log? 
Do you have the possibility to check this on Apache too, to make sure it's not a Nginx-related problem?

**Comment by rhukster** [comment]
What does your nginx configuration look like?

**Comment by signorekai** [comment]
Yes, path/to/grav is a fake path I added; am in staging and prefer not to leak out the url.

My nginx config is as follows:
````
server {
	listen 80 default_server;
	listen [::]:80 default_server ipv6only=on;

	root /usr/share/nginx/html/domain.tld;
	index index.php index.html index.htm;

	# Make site accessible from http://localhost/
	server_name domain.tld www.domain.tld;

	location / {
		try_files $uri $uri/ =404;
	}

	error_page 404 /404.html;
	error_page 500 502 503 504 /50x.html;
	location = /50x.html {
		root /usr/share/nginx/html; 
	}

	location ~ \.php$ {
		try_files $uri =404;
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass unix:/var/run/php5-fpm.sock;
		fastcgi_index index.php;
		include fastcgi_params;
	}
    
    location /demo/grav {
        index  index.php;
        if (!-e $request_filename){ rewrite ^(.*)$ /demo/grav/$2 last; }
        try_files $uri $uri/ /index.php?$args;
    }

    location /demo/grav/user {
        rewrite ^/user/accounts/(.*)$ /error redirect;
        rewrite ^/user/config/(.*)$ /error redirect;
        rewrite ^/user/(.*)\.(txt|md|html|php|yaml|json|twig|sh|bat)$ /error redirect;
    }

    location /demo/grav/cache {
    rewrite ^/cache/(.*) /error redirect;
    }

    location /demo/grav/bin {
        rewrite ^/bin/(.*)$ /error redirect;
    }

    location /demo/grav/backup {
    rewrite ^/backup/(.*) /error redirect;
    }

    location /demo/grav/system {
        rewrite ^/system/(.*)\.(txt|md|html|php|yaml|json|twig|sh|bat)$ /error redirect;
    }

    location /demo/grav/vendor {
        rewrite ^/vendor/(.*)\.(txt|md|html|php|yaml|json|twig|sh|bat)$ /error redirect;
    }

}
````

My grav is installed in ````demo/grav````.

**Comment by signorekai** [comment]
Also, just in case:

````php -v```` outputs the following:

````
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
````

**Comment by signorekai** [comment]
@flaviocopes I'll see if I can spin up a Apache droplet to test it out.

**Comment by flaviocopes** [comment]
I have no troubles with your nginx.conf general setup. I just changed the port and the PHP interpreter, using the MAMP one, and the paths relative to my folders setup. 

```

    server {
        listen 8776 default_server;


        root /Users/flavio/www;
        index index.php index.html index.htm;

        # Make site accessible from http://localhost/
        server_name localhost;

        location / {
            try_files $uri $uri/ =404;
        }

        error_page 404 /404.html;
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }

        ## Begin - PHP
        location ~ \.php$ {
            # Choose either a socket or TCP/IP address
            # fastcgi_pass unix:/var/run/php5-fpm.sock;
            fastcgi_pass unix:/Applications/MAMP/Library/logs/fastcgi/nginxFastCGI.sock;

            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
        }
        ## End - PHP

        location /grav {
            index  index.php;
            if (!-e $request_filename){ rewrite ^(.*)$ /grav/$2 last; }
            try_files $uri $uri/ /index.php?$args;
        }

        location /grav/user {
            rewrite ^/user/accounts/(.*)$ /error redirect;
            rewrite ^/user/config/(.*)$ /error redirect;
            rewrite ^/user/(.*)\.(txt|md|html|php|yaml|json|twig|sh|bat)$ /error redirect;
        }

        location /grav/cache {
        rewrite ^/cache/(.*) /error redirect;
        }

        location /grav/bin {
            rewrite ^/bin/(.*)$ /error redirect;
        }

        location /grav/backup {
        rewrite ^/backup/(.*) /error redirect;
        }

        location /grav/system {
            rewrite ^/system/(.*)\.(txt|md|html|php|yaml|json|twig|sh|bat)$ /error redirect;
        }

        location /grav/vendor {
            rewrite ^/vendor/(.*)\.(txt|md|html|php|yaml|json|twig|sh|bat)$ /error redirect;
        }

    }
```

The `nginx.conf` provided in the Grav root folder works fine or also that has issues for you?

**Comment by signorekai** [comment]
````
server {
	listen 80 default_server;
	listen [::]:80 default_server ipv6only=on;

	root /usr/share/nginx/html/domain.tld;
	index index.php index.html index.htm;

	# Make site accessible from http://localhost/
	server_name domain.tld;

	location / {
		try_files $uri $uri/ =404;
	}
    
    location /demo/grav {
        index index.php;
        if (!-e $request_filename){ rewrite ^(.*)$ /demo/grav/$2 last; }
        try_files $uri $uri/ /index.php?$args; 
    }

	error_page 404 /404.html;
	error_page 500 502 503 504 /50x.html;
	location = /50x.html {
		root /usr/share/nginx/html; 
	}

	location ~ \.php$ {
		try_files $uri =404;
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass unix:/var/run/php5-fpm.sock;
		fastcgi_index index.php;
		include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
	}

    ## Begin - Security
    # deny all direct access for these folders
    location ~* /demo/grav/(.git|cache|bin|logs|backups)/.*$ { return 403; }
    # deny running scripts inside core system folders
    location ~* /demo/grav/(system|vendor)/.*\.(txt|xml|md|html|yaml|php|pl|py|cgi|twig|sh|bat)$ { return 403; }
    # deny running scripts inside user folder
    location ~* /demo/grav/user/.*\.(txt|md|yaml|php|pl|py|cgi|twig|sh|bat)$ { return 403; }
    # deny access to specific files in the root folder
    location ~ /demo/grav/(LICENSE.txt|composer.lock|composer.json|nginx.conf|web.config|htaccess.txt|\.htaccess) { return 403; }
    ## End - Security
}
````

Updated nginx config, same issue.

**Comment by rhukster** [comment]
This must be an nginx configuration/setup issue on your end because I have the stock Grav nginx.conf setup on my raspberry pi test server, and it works fine, even when using params such as: `http://pi.dev/grav/tag:city`

Perhaps you can provide us with the full **page's worth of errors** in case there is anything in there that indicates what the issue is.

**Comment by signorekai** [comment]
It's bizarre, I just installed the same skeleton on another VM running an almost identical image, and it works without any errors. I'll try re-installing and see if it solves anything.

**Comment by signorekai** [comment]
So I re-installed `grav-skeleton-woo-site` and the url parameters are working now, weirdly.

Thanks @flaviocopes and @rhukster for your help!
